// Package gtk was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package gtk

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/internal/core"
	"github.com/jwijenbergh/puregotk/v4/gio"
	"github.com/jwijenbergh/puregotk/v4/glib"
	"github.com/jwijenbergh/puregotk/v4/gobject"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type AlertDialogClass struct {
	_ structs.HostLayout

	ParentClass uintptr
}

func (x *AlertDialogClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

// Collects the arguments that are needed to present a message to the user.
//
// The message is shown with the [method@Gtk.AlertDialog.choose]
// function.
//
// If you don't need to wait for a button to be clicked, you can use
// [method@Gtk.AlertDialog.show].
type AlertDialog struct {
	gobject.Object
}

var xAlertDialogGLibType func() types.GType

func AlertDialogGLibType() types.GType {
	return xAlertDialogGLibType()
}

func AlertDialogNewFromInternalPtr(ptr uintptr) *AlertDialog {
	cls := &AlertDialog{}
	cls.Ptr = ptr
	return cls
}

var xNewAlertDialog func(string, ...interface{}) uintptr

// Creates a new `GtkAlertDialog` object.
//
// The message will be set to the formatted string
// resulting from the arguments.
func NewAlertDialog(FormatVar string, varArgs ...interface{}) *AlertDialog {
	var cls *AlertDialog

	cret := xNewAlertDialog(FormatVar, varArgs...)

	if cret == 0 {
		return nil
	}
	cls = &AlertDialog{}
	cls.Ptr = cret
	return cls
}

var xAlertDialogChoose func(uintptr, uintptr, uintptr, uintptr, uintptr)

// Shows the alert to the user.
//
// It is ok to pass `NULL` for the callback if the alert
// does not have more than one button. A simpler API for
// this case is [method@Gtk.AlertDialog.show].
func (x *AlertDialog) Choose(ParentVar *Window, CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {

	xAlertDialogChoose(x.GoPointer(), ParentVar.GoPointer(), CancellableVar.GoPointer(), glib.NewCallback(CallbackVar), UserDataVar)

}

var xAlertDialogChooseFinish func(uintptr, uintptr, **glib.Error) int

// Finishes the [method@Gtk.AlertDialog.choose] call.
func (x *AlertDialog) ChooseFinish(ResultVar gio.AsyncResult) (int, error) {
	var cerr *glib.Error

	cret := xAlertDialogChooseFinish(x.GoPointer(), ResultVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xAlertDialogGetButtons func(uintptr) []string

// Returns the button labels for the alert.
func (x *AlertDialog) GetButtons() []string {

	cret := xAlertDialogGetButtons(x.GoPointer())
	return cret
}

var xAlertDialogGetCancelButton func(uintptr) int

// Returns the index of the cancel button.
func (x *AlertDialog) GetCancelButton() int {

	cret := xAlertDialogGetCancelButton(x.GoPointer())
	return cret
}

var xAlertDialogGetDefaultButton func(uintptr) int

// Returns the index of the default button.
func (x *AlertDialog) GetDefaultButton() int {

	cret := xAlertDialogGetDefaultButton(x.GoPointer())
	return cret
}

var xAlertDialogGetDetail func(uintptr) string

// Returns the detail text that will be shown in the alert.
func (x *AlertDialog) GetDetail() string {

	cret := xAlertDialogGetDetail(x.GoPointer())
	return cret
}

var xAlertDialogGetMessage func(uintptr) string

// Returns the message that will be shown in the alert.
func (x *AlertDialog) GetMessage() string {

	cret := xAlertDialogGetMessage(x.GoPointer())
	return cret
}

var xAlertDialogGetModal func(uintptr) bool

// Returns whether the alert blocks interaction
// with the parent window while it is presented.
func (x *AlertDialog) GetModal() bool {

	cret := xAlertDialogGetModal(x.GoPointer())
	return cret
}

var xAlertDialogSetButtons func(uintptr, []string)

// Sets the button labels for the alert.
func (x *AlertDialog) SetButtons(LabelsVar []string) {

	xAlertDialogSetButtons(x.GoPointer(), LabelsVar)

}

var xAlertDialogSetCancelButton func(uintptr, int)

// Sets the index of the cancel button.
//
// See [property@Gtk.AlertDialog:cancel-button] for
// details of how this value is used.
func (x *AlertDialog) SetCancelButton(ButtonVar int) {

	xAlertDialogSetCancelButton(x.GoPointer(), ButtonVar)

}

var xAlertDialogSetDefaultButton func(uintptr, int)

// Sets the index of the default button.
//
// See [property@Gtk.AlertDialog:default-button] for
// details of how this value is used.
func (x *AlertDialog) SetDefaultButton(ButtonVar int) {

	xAlertDialogSetDefaultButton(x.GoPointer(), ButtonVar)

}

var xAlertDialogSetDetail func(uintptr, string)

// Sets the detail text that will be shown in the alert.
func (x *AlertDialog) SetDetail(DetailVar string) {

	xAlertDialogSetDetail(x.GoPointer(), DetailVar)

}

var xAlertDialogSetMessage func(uintptr, string)

// Sets the message that will be shown in the alert.
func (x *AlertDialog) SetMessage(MessageVar string) {

	xAlertDialogSetMessage(x.GoPointer(), MessageVar)

}

var xAlertDialogSetModal func(uintptr, bool)

// Sets whether the alert blocks interaction
// with the parent window while it is presented.
func (x *AlertDialog) SetModal(ModalVar bool) {

	xAlertDialogSetModal(x.GoPointer(), ModalVar)

}

var xAlertDialogShow func(uintptr, uintptr)

// Shows the alert to the user.
//
// This function is a simpler version of [method@Gtk.AlertDialog.choose]
// intended for dialogs with a single button.
//
// If you want to cancel the dialog or if the alert has more than one
// button, you should use that function instead and provide it with a
// [class@Gio.Cancellable] and callback respectively.
func (x *AlertDialog) Show(ParentVar *Window) {

	xAlertDialogShow(x.GoPointer(), ParentVar.GoPointer())

}

func (c *AlertDialog) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *AlertDialog) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	lib, err := purego.Dlopen(core.GetPath("GTK"), purego.RTLD_NOW|purego.RTLD_GLOBAL)
	if err != nil {
		panic(err)
	}

	core.PuregoSafeRegister(&xAlertDialogGLibType, lib, "gtk_alert_dialog_get_type")

	core.PuregoSafeRegister(&xNewAlertDialog, lib, "gtk_alert_dialog_new")

	core.PuregoSafeRegister(&xAlertDialogChoose, lib, "gtk_alert_dialog_choose")
	core.PuregoSafeRegister(&xAlertDialogChooseFinish, lib, "gtk_alert_dialog_choose_finish")
	core.PuregoSafeRegister(&xAlertDialogGetButtons, lib, "gtk_alert_dialog_get_buttons")
	core.PuregoSafeRegister(&xAlertDialogGetCancelButton, lib, "gtk_alert_dialog_get_cancel_button")
	core.PuregoSafeRegister(&xAlertDialogGetDefaultButton, lib, "gtk_alert_dialog_get_default_button")
	core.PuregoSafeRegister(&xAlertDialogGetDetail, lib, "gtk_alert_dialog_get_detail")
	core.PuregoSafeRegister(&xAlertDialogGetMessage, lib, "gtk_alert_dialog_get_message")
	core.PuregoSafeRegister(&xAlertDialogGetModal, lib, "gtk_alert_dialog_get_modal")
	core.PuregoSafeRegister(&xAlertDialogSetButtons, lib, "gtk_alert_dialog_set_buttons")
	core.PuregoSafeRegister(&xAlertDialogSetCancelButton, lib, "gtk_alert_dialog_set_cancel_button")
	core.PuregoSafeRegister(&xAlertDialogSetDefaultButton, lib, "gtk_alert_dialog_set_default_button")
	core.PuregoSafeRegister(&xAlertDialogSetDetail, lib, "gtk_alert_dialog_set_detail")
	core.PuregoSafeRegister(&xAlertDialogSetMessage, lib, "gtk_alert_dialog_set_message")
	core.PuregoSafeRegister(&xAlertDialogSetModal, lib, "gtk_alert_dialog_set_modal")
	core.PuregoSafeRegister(&xAlertDialogShow, lib, "gtk_alert_dialog_show")

}
