// Package gtk was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package gtk

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/internal/core"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

// The interface vtable for accessible objects containing text.
type AccessibleTextInterface struct {
	_ structs.HostLayout

	GIface uintptr
}

func (x *AccessibleTextInterface) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

// A range inside the text of an accessible object.
type AccessibleTextRange struct {
	_ structs.HostLayout

	Start uint

	Length uint
}

func (x *AccessibleTextRange) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

// An interface for accessible objects containing formatted text.
//
// The `GtkAccessibleText` interfaces is meant to be implemented by accessible
// objects that have text formatted with attributes, or non-trivial text contents.
//
// You should use the [enum@Gtk.AccessibleProperty.LABEL] or the
// [enum@Gtk.AccessibleProperty.DESCRIPTION] properties for accessible
// objects containing simple, unformatted text.
type AccessibleText interface {
	GoPointer() uintptr
	SetGoPointer(uintptr)
	UpdateCaretPosition()
	UpdateContents(ChangeVar AccessibleTextContentChange, StartVar uint, EndVar uint)
	UpdateSelectionBound()
}

var xAccessibleTextGLibType func() types.GType

func AccessibleTextGLibType() types.GType {
	return xAccessibleTextGLibType()
}

type AccessibleTextBase struct {
	Ptr uintptr
}

func (x *AccessibleTextBase) GoPointer() uintptr {
	if x == nil {
		return 0
	}
	return x.Ptr
}

func (x *AccessibleTextBase) SetGoPointer(ptr uintptr) {
	x.Ptr = ptr
}

// Updates the position of the caret.
//
// Implementations of the `GtkAccessibleText` interface should call this
// function every time the caret has moved, in order to notify assistive
// technologies.
func (x *AccessibleTextBase) UpdateCaretPosition() {

	XGtkAccessibleTextUpdateCaretPosition(x.GoPointer())

}

// Notifies assistive technologies of a change in contents.
//
// Implementations of the `GtkAccessibleText` interface should call this
// function every time their contents change as the result of an operation,
// like an insertion or a removal.
//
// Note: If the change is a deletion, this function must be called *before*
// removing the contents, if it is an insertion, it must be called *after*
// inserting the new contents.
func (x *AccessibleTextBase) UpdateContents(ChangeVar AccessibleTextContentChange, StartVar uint, EndVar uint) {

	XGtkAccessibleTextUpdateContents(x.GoPointer(), ChangeVar, StartVar, EndVar)

}

// Updates the boundary of the selection.
//
// Implementations of the `GtkAccessibleText` interface should call this
// function every time the selection has moved, in order to notify assistive
// technologies.
func (x *AccessibleTextBase) UpdateSelectionBound() {

	XGtkAccessibleTextUpdateSelectionBound(x.GoPointer())

}

var XGtkAccessibleTextUpdateCaretPosition func(uintptr)
var XGtkAccessibleTextUpdateContents func(uintptr, AccessibleTextContentChange, uint, uint)
var XGtkAccessibleTextUpdateSelectionBound func(uintptr)

const (
	// An attribute for the background color, expressed as an RGB value
	// encoded in a string using the format: `{r8},{g8},{b8}`.
	ACCESSIBLE_ATTRIBUTE_BACKGROUND string = "bg-color"
	// An attribute for the font family name.
	ACCESSIBLE_ATTRIBUTE_FAMILY string = "family-name"
	// An attribute for the foreground color, expressed as an RGB value
	// encoded in a string using the format: `{r8},{g8},{b8}`.
	ACCESSIBLE_ATTRIBUTE_FOREGROUND string = "fg-color"
	// An attribute for the overline style.
	//
	// Possible values are:
	//
	// - [const@Gtk.ACCESSIBLE_ATTRIBUTE_OVERLINE_NONE]
	// - [const@Gtk.ACCESSIBLE_ATTRIBUTE_OVERLINE_SINGLE]
	ACCESSIBLE_ATTRIBUTE_OVERLINE string = "overline"
	// The "none" overline value for [const@Gtk.ACCESSIBLE_ATTRIBUTE_OVERLINE].
	ACCESSIBLE_ATTRIBUTE_OVERLINE_NONE string = "none"
	// The "single" overline value for [const@Gtk.ACCESSIBLE_ATTRIBUTE_OVERLINE].
	ACCESSIBLE_ATTRIBUTE_OVERLINE_SINGLE string = "single"
	// An attribute for the font size, expressed in points.
	ACCESSIBLE_ATTRIBUTE_SIZE string = "size"
	// An attribute for the font stretch type.
	//
	// Possible values are:
	//
	// - [const@Gtk.ACCESSIBLE_ATTRIBUTE_STRETCH_ULTRA_CONDENSED]
	// - [const@Gtk.ACCESSIBLE_ATTRIBUTE_STRETCH_EXTRA_CONDENSED]
	// - [const@Gtk.ACCESSIBLE_ATTRIBUTE_STRETCH_CONDENSED]
	// - [const@Gtk.ACCESSIBLE_ATTRIBUTE_STRETCH_SEMI_CONDENSED]
	ACCESSIBLE_ATTRIBUTE_STRETCH string = "stretch"
	// The "condensed" stretch value for [const@Gtk.ACCESSIBLE_ATTRIBUTE_STRETCH].
	ACCESSIBLE_ATTRIBUTE_STRETCH_CONDENSED string = "condensed"
	// The "expanded" stretch value for [const@Gtk.ACCESSIBLE_ATTRIBUTE_STRETCH].
	ACCESSIBLE_ATTRIBUTE_STRETCH_EXPANDED string = "expanded"
	// The "extra condensed" stretch value for [const@Gtk.ACCESSIBLE_ATTRIBUTE_STRETCH].
	ACCESSIBLE_ATTRIBUTE_STRETCH_EXTRA_CONDENSED string = "extra_condensed"
	// The "extra expanded" stretch value for [const@Gtk.ACCESSIBLE_ATTRIBUTE_STRETCH].
	ACCESSIBLE_ATTRIBUTE_STRETCH_EXTRA_EXPANDED string = "extra_expanded"
	// The "normal" stretch value for [const@Gtk.ACCESSIBLE_ATTRIBUTE_STRETCH].
	ACCESSIBLE_ATTRIBUTE_STRETCH_NORMAL string = "normal"
	// The "semi condensed" stretch value for [const@Gtk.ACCESSIBLE_ATTRIBUTE_STRETCH].
	ACCESSIBLE_ATTRIBUTE_STRETCH_SEMI_CONDENSED string = "semi_condensed"
	// The "semi expanded" stretch value for [const@Gtk.ACCESSIBLE_ATTRIBUTE_STRETCH].
	ACCESSIBLE_ATTRIBUTE_STRETCH_SEMI_EXPANDED string = "semi_expanded"
	// The "ultra condensed" stretch value for [const@Gtk.ACCESSIBLE_ATTRIBUTE_STRETCH].
	ACCESSIBLE_ATTRIBUTE_STRETCH_ULTRA_CONDENSED string = "ultra_condensed"
	// The "ultra expanded" stretch value for [const@Gtk.ACCESSIBLE_ATTRIBUTE_STRETCH].
	ACCESSIBLE_ATTRIBUTE_STRETCH_ULTRA_EXPANDED string = "ultra_expanded"
	// An attribute for strikethrough text.
	//
	// Possible values are `true` or `false`.
	ACCESSIBLE_ATTRIBUTE_STRIKETHROUGH string = "strikethrough"
	// An attribute for the font style.
	//
	// Possible values are:
	//
	// - [const@Gtk.ACCESSIBLE_ATTRIBUTE_STYLE_NORMAL]
	// - [const@Gtk.ACCESSIBLE_ATTRIBUTE_STYLE_OBLIQUE]
	// - [const@Gtk.ACCESSIBLE_ATTRIBUTE_STYLE_ITALIC]
	ACCESSIBLE_ATTRIBUTE_STYLE string = "style"
	// The "italic" style value for [const@Gtk.ACCESSIBLE_ATTRIBUTE_STYLE].
	ACCESSIBLE_ATTRIBUTE_STYLE_ITALIC string = "italic"
	// The "normal" style value for [const@Gtk.ACCESSIBLE_ATTRIBUTE_STYLE].
	ACCESSIBLE_ATTRIBUTE_STYLE_NORMAL string = "normal"
	// The "oblique" style value for [const@Gtk.ACCESSIBLE_ATTRIBUTE_STYLE].
	ACCESSIBLE_ATTRIBUTE_STYLE_OBLIQUE string = "oblique"
	// An attribute for the underline style.
	//
	// Possible values are:
	//
	// - [const@Gtk.ACCESSIBLE_ATTRIBUTE_UNDERLINE_NONE]
	// - [const@Gtk.ACCESSIBLE_ATTRIBUTE_UNDERLINE_SINGLE]
	// - [const@Gtk.ACCESSIBLE_ATTRIBUTE_UNDERLINE_DOUBLE]
	// - [const@Gtk.ACCESSIBLE_ATTRIBUTE_UNDERLINE_ERROR]
	ACCESSIBLE_ATTRIBUTE_UNDERLINE string = "underline"
	// The "double" underline value for [const@Gtk.ACCESSIBLE_ATTRIBUTE_UNDERLINE].
	ACCESSIBLE_ATTRIBUTE_UNDERLINE_DOUBLE string = "double"
	// The "error" underline value for [const@Gtk.ACCESSIBLE_ATTRIBUTE_UNDERLINE].
	ACCESSIBLE_ATTRIBUTE_UNDERLINE_ERROR string = "error"
	// The "none" underline value for [const@Gtk.ACCESSIBLE_ATTRIBUTE_UNDERLINE].
	ACCESSIBLE_ATTRIBUTE_UNDERLINE_NONE string = "none"
	// The "single" underline value for [const@Gtk.ACCESSIBLE_ATTRIBUTE_UNDERLINE].
	ACCESSIBLE_ATTRIBUTE_UNDERLINE_SINGLE string = "single"
	// An attribute for the font variant.
	//
	// Possible values are:
	//
	// - [const@Gtk.ACCESSIBLE_ATTRIBUTE_VARIANT_SMALL_CAPS]
	// - [const@Gtk.ACCESSIBLE_ATTRIBUTE_VARIANT_ALL_SMALL_CAPS]
	// - [const@Gtk.ACCESSIBLE_ATTRIBUTE_VARIANT_PETITE_CAPS]
	// - [const@Gtk.ACCESSIBLE_ATTRIBUTE_VARIANT_ALL_PETITE_CAPS]
	// - [const@Gtk.ACCESSIBLE_ATTRIBUTE_VARIANT_UNICASE]
	// - [const@Gtk.ACCESSIBLE_ATTRIBUTE_VARIANT_TITLE_CAPS]
	ACCESSIBLE_ATTRIBUTE_VARIANT string = "variant"
	// The "all petite caps" variant value for [const@Gtk.ACCESSIBLE_ATTRIBUTE_VARIANT].
	ACCESSIBLE_ATTRIBUTE_VARIANT_ALL_PETITE_CAPS string = "all-petite-caps"
	// The "all small caps" variant value for [const@Gtk.ACCESSIBLE_ATTRIBUTE_VARIANT].
	ACCESSIBLE_ATTRIBUTE_VARIANT_ALL_SMALL_CAPS string = "all-small-caps"
	// The "petite caps" variant value for [const@Gtk.ACCESSIBLE_ATTRIBUTE_VARIANT].
	ACCESSIBLE_ATTRIBUTE_VARIANT_PETITE_CAPS string = "petite-caps"
	// The "small caps" variant value for [const@Gtk.ACCESSIBLE_ATTRIBUTE_VARIANT].
	ACCESSIBLE_ATTRIBUTE_VARIANT_SMALL_CAPS string = "small-caps"
	// The "title caps" variant value for [const@Gtk.ACCESSIBLE_ATTRIBUTE_VARIANT].
	ACCESSIBLE_ATTRIBUTE_VARIANT_TITLE_CAPS string = "title-caps"
	// The "unicase" variant value for [const@Gtk.ACCESSIBLE_ATTRIBUTE_VARIANT].
	ACCESSIBLE_ATTRIBUTE_VARIANT_UNICASE string = "unicase"
	// An attribute for the font weight.
	ACCESSIBLE_ATTRIBUTE_WEIGHT string = "weight"
)

// The type of contents change operation.
type AccessibleTextContentChange int

var xAccessibleTextContentChangeGLibType func() types.GType

func AccessibleTextContentChangeGLibType() types.GType {
	return xAccessibleTextContentChangeGLibType()
}

const (

	// contents change as the result of
	//   an insert operation
	AccessibleTextContentChangeInsertValue AccessibleTextContentChange = 0
	// contents change as the result of
	//   a remove operation
	AccessibleTextContentChangeRemoveValue AccessibleTextContentChange = 1
)

// The granularity for queries about the text contents of a [iface@Gtk.AccessibleText]
// implementation.
type AccessibleTextGranularity int

var xAccessibleTextGranularityGLibType func() types.GType

func AccessibleTextGranularityGLibType() types.GType {
	return xAccessibleTextGranularityGLibType()
}

const (

	// Use the boundary between
	//   characters (including non-printing characters)
	AccessibleTextGranularityCharacterValue AccessibleTextGranularity = 0
	// Use the boundary between words,
	//   starting from the beginning of the current word and ending at the
	//   beginning of the next word
	AccessibleTextGranularityWordValue AccessibleTextGranularity = 1
	// Use the boundary between
	//   sentences, starting from the beginning of the current sentence and
	//   ending at the beginning of the next sentence
	AccessibleTextGranularitySentenceValue AccessibleTextGranularity = 2
	// Use the boundary between lines,
	//   starting from the beginning of the current line and ending at the
	//   beginning of the next line
	AccessibleTextGranularityLineValue AccessibleTextGranularity = 3
	// Use the boundary between
	//   paragraphs, starting from the beginning of the current paragraph and
	//   ending at the beginning of the next paragraph
	AccessibleTextGranularityParagraphValue AccessibleTextGranularity = 4
)

func init() {
	lib, err := purego.Dlopen(core.GetPath("GTK"), purego.RTLD_NOW|purego.RTLD_GLOBAL)
	if err != nil {
		panic(err)
	}

	core.PuregoSafeRegister(&xAccessibleTextContentChangeGLibType, lib, "gtk_accessible_text_content_change_get_type")

	core.PuregoSafeRegister(&xAccessibleTextGranularityGLibType, lib, "gtk_accessible_text_granularity_get_type")

	core.PuregoSafeRegister(&xAccessibleTextGLibType, lib, "gtk_accessible_text_get_type")

	core.PuregoSafeRegister(&XGtkAccessibleTextUpdateCaretPosition, lib, "gtk_accessible_text_update_caret_position")
	core.PuregoSafeRegister(&XGtkAccessibleTextUpdateContents, lib, "gtk_accessible_text_update_contents")
	core.PuregoSafeRegister(&XGtkAccessibleTextUpdateSelectionBound, lib, "gtk_accessible_text_update_selection_bound")

}
