// Package gtk was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package gtk

import (
	"structs"
	"unsafe"
)

// Points at a location inside a CSS stream.
type CssLocation struct {
	_ structs.HostLayout

	Bytes uint

	Chars uint

	Lines uint

	LineBytes uint

	LineChars uint
}

func (x *CssLocation) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}
