// Package gtk was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package gtk

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/internal/core"
	"github.com/jwijenbergh/puregotk/v4/gdk"
	"github.com/jwijenbergh/puregotk/v4/gio"
	"github.com/jwijenbergh/puregotk/v4/glib"
	"github.com/jwijenbergh/puregotk/v4/gobject"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type ColorDialogClass struct {
	_ structs.HostLayout

	ParentClass uintptr
}

func (x *ColorDialogClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

// Asynchronous API to present a color chooser dialog.
//
// `GtkColorDialog` collects the arguments that are needed to present
// the dialog to the user, such as a title for the dialog and whether
// it should be modal.
//
// The dialog is shown with the [method@Gtk.ColorDialog.choose_rgba]
// function.
//
// See [class@Gtk.ColorDialogButton] for a convenient control
// that uses `GtkColorDialog` and presents the results.
type ColorDialog struct {
	gobject.Object
}

var xColorDialogGLibType func() types.GType

func ColorDialogGLibType() types.GType {
	return xColorDialogGLibType()
}

func ColorDialogNewFromInternalPtr(ptr uintptr) *ColorDialog {
	cls := &ColorDialog{}
	cls.Ptr = ptr
	return cls
}

var xNewColorDialog func() uintptr

// Creates a new `GtkColorDialog` object.
func NewColorDialog() *ColorDialog {
	var cls *ColorDialog

	cret := xNewColorDialog()

	if cret == 0 {
		return nil
	}
	cls = &ColorDialog{}
	cls.Ptr = cret
	return cls
}

var xColorDialogChooseRgba func(uintptr, uintptr, *gdk.RGBA, uintptr, uintptr, uintptr)

// Presents a color chooser dialog to the user.
func (x *ColorDialog) ChooseRgba(ParentVar *Window, InitialColorVar *gdk.RGBA, CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {

	xColorDialogChooseRgba(x.GoPointer(), ParentVar.GoPointer(), InitialColorVar, CancellableVar.GoPointer(), glib.NewCallback(CallbackVar), UserDataVar)

}

var xColorDialogChooseRgbaFinish func(uintptr, uintptr, **glib.Error) *gdk.RGBA

// Finishes the [method@Gtk.ColorDialog.choose_rgba] call
func (x *ColorDialog) ChooseRgbaFinish(ResultVar gio.AsyncResult) (*gdk.RGBA, error) {
	var cerr *glib.Error

	cret := xColorDialogChooseRgbaFinish(x.GoPointer(), ResultVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xColorDialogGetModal func(uintptr) bool

// Returns whether the color chooser dialog
// blocks interaction with the parent window
// while it is presented.
func (x *ColorDialog) GetModal() bool {

	cret := xColorDialogGetModal(x.GoPointer())
	return cret
}

var xColorDialogGetTitle func(uintptr) string

// Returns the title that will be shown on the
// color chooser dialog.
func (x *ColorDialog) GetTitle() string {

	cret := xColorDialogGetTitle(x.GoPointer())
	return cret
}

var xColorDialogGetWithAlpha func(uintptr) bool

// Returns whether colors may have alpha.
func (x *ColorDialog) GetWithAlpha() bool {

	cret := xColorDialogGetWithAlpha(x.GoPointer())
	return cret
}

var xColorDialogSetModal func(uintptr, bool)

// Sets whether the color chooser dialog
// blocks interaction with the parent window
// while it is presented.
func (x *ColorDialog) SetModal(ModalVar bool) {

	xColorDialogSetModal(x.GoPointer(), ModalVar)

}

var xColorDialogSetTitle func(uintptr, string)

// Sets the title that will be shown on the
// color chooser dialog.
func (x *ColorDialog) SetTitle(TitleVar string) {

	xColorDialogSetTitle(x.GoPointer(), TitleVar)

}

var xColorDialogSetWithAlpha func(uintptr, bool)

// Sets whether colors may have alpha.
func (x *ColorDialog) SetWithAlpha(WithAlphaVar bool) {

	xColorDialogSetWithAlpha(x.GoPointer(), WithAlphaVar)

}

func (c *ColorDialog) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *ColorDialog) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	lib, err := purego.Dlopen(core.GetPath("GTK"), purego.RTLD_NOW|purego.RTLD_GLOBAL)
	if err != nil {
		panic(err)
	}

	core.PuregoSafeRegister(&xColorDialogGLibType, lib, "gtk_color_dialog_get_type")

	core.PuregoSafeRegister(&xNewColorDialog, lib, "gtk_color_dialog_new")

	core.PuregoSafeRegister(&xColorDialogChooseRgba, lib, "gtk_color_dialog_choose_rgba")
	core.PuregoSafeRegister(&xColorDialogChooseRgbaFinish, lib, "gtk_color_dialog_choose_rgba_finish")
	core.PuregoSafeRegister(&xColorDialogGetModal, lib, "gtk_color_dialog_get_modal")
	core.PuregoSafeRegister(&xColorDialogGetTitle, lib, "gtk_color_dialog_get_title")
	core.PuregoSafeRegister(&xColorDialogGetWithAlpha, lib, "gtk_color_dialog_get_with_alpha")
	core.PuregoSafeRegister(&xColorDialogSetModal, lib, "gtk_color_dialog_set_modal")
	core.PuregoSafeRegister(&xColorDialogSetTitle, lib, "gtk_color_dialog_set_title")
	core.PuregoSafeRegister(&xColorDialogSetWithAlpha, lib, "gtk_color_dialog_set_with_alpha")

}
