// Package gtk was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package gtk

import (
	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/internal/core"
	"github.com/jwijenbergh/puregotk/v4/glib"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

// Error codes in the `GTK_DIALOG_ERROR` domain that can be returned
// by async dialog functions.
type DialogError int

var xDialogErrorGLibType func() types.GType

func DialogErrorGLibType() types.GType {
	return xDialogErrorGLibType()
}

const (

	// Generic error condition for when
	//   an operation fails and no more specific code is applicable
	DialogErrorFailedValue DialogError = 0
	// The async function call was cancelled
	//   via its `GCancellable`
	DialogErrorCancelledValue DialogError = 1
	// The operation was cancelled
	//   by the user (via a Cancel or Close button)
	DialogErrorDismissedValue DialogError = 2
)

var xDialogErrorQuark func() glib.Quark

// Registers an error quark for an operation that requires a dialog if
// necessary.
func DialogErrorQuark() glib.Quark {

	cret := xDialogErrorQuark()
	return cret
}

func init() {
	lib, err := purego.Dlopen(core.GetPath("GTK"), purego.RTLD_NOW|purego.RTLD_GLOBAL)
	if err != nil {
		panic(err)
	}

	core.PuregoSafeRegister(&xDialogErrorGLibType, lib, "gtk_dialog_error_get_type")

	core.PuregoSafeRegister(&xDialogErrorQuark, lib, "gtk_dialog_error_quark")

}
