// Package gtk was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package gtk

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/internal/core"
	"github.com/jwijenbergh/puregotk/v4/glib"
	"github.com/jwijenbergh/puregotk/v4/gobject"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
	"github.com/jwijenbergh/puregotk/v4/pango"
)

type FontDialogButtonClass struct {
	_ structs.HostLayout

	ParentClass uintptr
}

func (x *FontDialogButtonClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

// The level of granularity for the font selection.
//
// Depending on this value, the `PangoFontDescription` that
// is returned by [method@Gtk.FontDialogButton.get_font_desc]
// will have more or less fields set.
type FontLevel int

var xFontLevelGLibType func() types.GType

func FontLevelGLibType() types.GType {
	return xFontLevelGLibType()
}

const (

	// Select a font family
	FontLevelFamilyValue FontLevel = 0
	// Select a font face (i.e. a family and a style)
	FontLevelFaceValue FontLevel = 1
	// Select a font (i.e. a face with a size, and possibly font variations)
	FontLevelFontValue FontLevel = 2
	// Select a font and font features
	FontLevelFeaturesValue FontLevel = 3
)

// Opens a font chooser dialog to select a font.
//
// &lt;picture&gt;
//
//	&lt;source srcset="font-button-dark.png" media="(prefers-color-scheme: dark)"&gt;
//	&lt;img alt="An example GtkFontDialogButton" src="font-button.png"&gt;
//
// &lt;/picture&gt;
//
// It is suitable widget for selecting a font in a preference dialog.
//
// # CSS nodes
//
// ```
// fontbutton
// ╰── button.font
//
//	╰── [content]
//
// ```
//
// `GtkFontDialogButton` has a single CSS node with name fontbutton which
// contains a button node with the .font style class.
type FontDialogButton struct {
	Widget
}

var xFontDialogButtonGLibType func() types.GType

func FontDialogButtonGLibType() types.GType {
	return xFontDialogButtonGLibType()
}

func FontDialogButtonNewFromInternalPtr(ptr uintptr) *FontDialogButton {
	cls := &FontDialogButton{}
	cls.Ptr = ptr
	return cls
}

var xNewFontDialogButton func(uintptr) uintptr

// Creates a new `GtkFontDialogButton` with the
// given `GtkFontDialog`.
//
// You can pass `NULL` to this function and set a `GtkFontDialog`
// later. The button will be insensitive until that happens.
func NewFontDialogButton(DialogVar *FontDialog) *FontDialogButton {
	var cls *FontDialogButton

	cret := xNewFontDialogButton(DialogVar.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &FontDialogButton{}
	cls.Ptr = cret
	return cls
}

var xFontDialogButtonGetDialog func(uintptr) uintptr

// Returns the `GtkFontDialog` of @self.
func (x *FontDialogButton) GetDialog() *FontDialog {
	var cls *FontDialog

	cret := xFontDialogButtonGetDialog(x.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &FontDialog{}
	cls.Ptr = cret
	return cls
}

var xFontDialogButtonGetFontDesc func(uintptr) *pango.FontDescription

// Returns the font of the button.
//
// This function is what should be used to obtain
// the font that was chosen by the user. To get
// informed about changes, listen to "notify::font-desc".
func (x *FontDialogButton) GetFontDesc() *pango.FontDescription {

	cret := xFontDialogButtonGetFontDesc(x.GoPointer())
	return cret
}

var xFontDialogButtonGetFontFeatures func(uintptr) string

// Returns the font features of the button.
//
// This function is what should be used to obtain the font features
// that were chosen by the user. To get informed about changes, listen
// to "notify::font-features".
//
// Note that the button will only let users choose font features
// if [property@Gtk.FontDialogButton:level] is set to
// `GTK_FONT_LEVEL_FEATURES`.
func (x *FontDialogButton) GetFontFeatures() string {

	cret := xFontDialogButtonGetFontFeatures(x.GoPointer())
	return cret
}

var xFontDialogButtonGetLanguage func(uintptr) *pango.Language

// Returns the language that is used for font features.
func (x *FontDialogButton) GetLanguage() *pango.Language {

	cret := xFontDialogButtonGetLanguage(x.GoPointer())
	return cret
}

var xFontDialogButtonGetLevel func(uintptr) FontLevel

// Returns the level of detail at which this dialog
// lets the user select fonts.
func (x *FontDialogButton) GetLevel() FontLevel {

	cret := xFontDialogButtonGetLevel(x.GoPointer())
	return cret
}

var xFontDialogButtonGetUseFont func(uintptr) bool

// Returns whether the selected font is used in the label.
func (x *FontDialogButton) GetUseFont() bool {

	cret := xFontDialogButtonGetUseFont(x.GoPointer())
	return cret
}

var xFontDialogButtonGetUseSize func(uintptr) bool

// Returns whether the selected font size is used in the label.
func (x *FontDialogButton) GetUseSize() bool {

	cret := xFontDialogButtonGetUseSize(x.GoPointer())
	return cret
}

var xFontDialogButtonSetDialog func(uintptr, uintptr)

// Sets a `GtkFontDialog` object to use for
// creating the font chooser dialog that is
// presented when the user clicks the button.
func (x *FontDialogButton) SetDialog(DialogVar *FontDialog) {

	xFontDialogButtonSetDialog(x.GoPointer(), DialogVar.GoPointer())

}

var xFontDialogButtonSetFontDesc func(uintptr, *pango.FontDescription)

// Sets the font of the button.
func (x *FontDialogButton) SetFontDesc(FontDescVar *pango.FontDescription) {

	xFontDialogButtonSetFontDesc(x.GoPointer(), FontDescVar)

}

var xFontDialogButtonSetFontFeatures func(uintptr, string)

// Sets the font features of the button.
func (x *FontDialogButton) SetFontFeatures(FontFeaturesVar string) {

	xFontDialogButtonSetFontFeatures(x.GoPointer(), FontFeaturesVar)

}

var xFontDialogButtonSetLanguage func(uintptr, *pango.Language)

// Sets the language to use for font features.
func (x *FontDialogButton) SetLanguage(LanguageVar *pango.Language) {

	xFontDialogButtonSetLanguage(x.GoPointer(), LanguageVar)

}

var xFontDialogButtonSetLevel func(uintptr, FontLevel)

// Sets the level of detail at which this dialog
// lets the user select fonts.
func (x *FontDialogButton) SetLevel(LevelVar FontLevel) {

	xFontDialogButtonSetLevel(x.GoPointer(), LevelVar)

}

var xFontDialogButtonSetUseFont func(uintptr, bool)

// If @use_font is `TRUE`, the font name will be written
// using the selected font.
func (x *FontDialogButton) SetUseFont(UseFontVar bool) {

	xFontDialogButtonSetUseFont(x.GoPointer(), UseFontVar)

}

var xFontDialogButtonSetUseSize func(uintptr, bool)

// If @use_size is `TRUE`, the font name will be written
// using the selected font size.
func (x *FontDialogButton) SetUseSize(UseSizeVar bool) {

	xFontDialogButtonSetUseSize(x.GoPointer(), UseSizeVar)

}

func (c *FontDialogButton) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *FontDialogButton) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

// Emitted when the font dialog button is activated.
//
// The `::activate` signal on `GtkFontDialogButton` is an action signal
// and emitting it causes the button to pop up its dialog.
func (x *FontDialogButton) ConnectActivate(cb *func(FontDialogButton)) uint32 {
	cbPtr := uintptr(unsafe.Pointer(cb))
	if cbRefPtr, ok := glib.GetCallback(cbPtr); ok {
		return gobject.SignalConnect(x.GoPointer(), "activate", cbRefPtr)
	}

	fcb := func(clsPtr uintptr) {
		fa := FontDialogButton{}
		fa.Ptr = clsPtr
		cbFn := *cb

		cbFn(fa)

	}
	cbRefPtr := purego.NewCallback(fcb)
	glib.SaveCallback(cbPtr, cbRefPtr)
	return gobject.SignalConnect(x.GoPointer(), "activate", cbRefPtr)
}

// Requests the user's screen reader to announce the given message.
//
// This kind of notification is useful for messages that
// either have only a visual representation or that are not
// exposed visually at all, e.g. a notification about a
// successful operation.
//
// Also, by using this API, you can ensure that the message
// does not interrupts the user's current screen reader output.
func (x *FontDialogButton) Announce(MessageVar string, PriorityVar AccessibleAnnouncementPriority) {

	XGtkAccessibleAnnounce(x.GoPointer(), MessageVar, PriorityVar)

}

// Retrieves the accessible parent for an accessible object.
//
// This function returns `NULL` for top level widgets.
func (x *FontDialogButton) GetAccessibleParent() *AccessibleBase {
	var cls *AccessibleBase

	cret := XGtkAccessibleGetAccessibleParent(x.GoPointer())

	if cret == 0 {
		return nil
	}
	cls = &AccessibleBase{}
	cls.Ptr = cret
	return cls
}

// Retrieves the accessible role of an accessible object.
func (x *FontDialogButton) GetAccessibleRole() AccessibleRole {

	cret := XGtkAccessibleGetAccessibleRole(x.GoPointer())
	return cret
}

// Retrieves the implementation for the given accessible object.
func (x *FontDialogButton) GetAtContext() *ATContext {
	var cls *ATContext

	cret := XGtkAccessibleGetAtContext(x.GoPointer())

	if cret == 0 {
		return nil
	}
	cls = &ATContext{}
	cls.Ptr = cret
	return cls
}

// Queries the coordinates and dimensions of this accessible
//
// This functionality can be overridden by `GtkAccessible`
// implementations, e.g. to get the bounds from an ignored
// child widget.
func (x *FontDialogButton) GetBounds(XVar int, YVar int, WidthVar int, HeightVar int) bool {

	cret := XGtkAccessibleGetBounds(x.GoPointer(), XVar, YVar, WidthVar, HeightVar)
	return cret
}

// Retrieves the first accessible child of an accessible object.
func (x *FontDialogButton) GetFirstAccessibleChild() *AccessibleBase {
	var cls *AccessibleBase

	cret := XGtkAccessibleGetFirstAccessibleChild(x.GoPointer())

	if cret == 0 {
		return nil
	}
	cls = &AccessibleBase{}
	cls.Ptr = cret
	return cls
}

// Retrieves the next accessible sibling of an accessible object
func (x *FontDialogButton) GetNextAccessibleSibling() *AccessibleBase {
	var cls *AccessibleBase

	cret := XGtkAccessibleGetNextAccessibleSibling(x.GoPointer())

	if cret == 0 {
		return nil
	}
	cls = &AccessibleBase{}
	cls.Ptr = cret
	return cls
}

// Queries a platform state, such as focus.
//
// This functionality can be overridden by `GtkAccessible`
// implementations, e.g. to get platform state from an ignored
// child widget, as is the case for `GtkText` wrappers.
func (x *FontDialogButton) GetPlatformState(StateVar AccessiblePlatformState) bool {

	cret := XGtkAccessibleGetPlatformState(x.GoPointer(), StateVar)
	return cret
}

// Resets the accessible property to its default value.
func (x *FontDialogButton) ResetProperty(PropertyVar AccessibleProperty) {

	XGtkAccessibleResetProperty(x.GoPointer(), PropertyVar)

}

// Resets the accessible relation to its default value.
func (x *FontDialogButton) ResetRelation(RelationVar AccessibleRelation) {

	XGtkAccessibleResetRelation(x.GoPointer(), RelationVar)

}

// Resets the accessible state to its default value.
func (x *FontDialogButton) ResetState(StateVar AccessibleState) {

	XGtkAccessibleResetState(x.GoPointer(), StateVar)

}

// Sets the parent and sibling of an accessible object.
//
// This function is meant to be used by accessible implementations that are
// not part of the widget hierarchy, and but act as a logical bridge between
// widgets. For instance, if a widget creates an object that holds metadata
// for each child, and you want that object to implement the `GtkAccessible`
// interface, you will use this function to ensure that the parent of each
// child widget is the metadata object, and the parent of each metadata
// object is the container widget.
func (x *FontDialogButton) SetAccessibleParent(ParentVar Accessible, NextSiblingVar Accessible) {

	XGtkAccessibleSetAccessibleParent(x.GoPointer(), ParentVar.GoPointer(), NextSiblingVar.GoPointer())

}

// Updates the next accessible sibling.
//
// That might be useful when a new child of a custom accessible
// is created, and it needs to be linked to a previous child.
func (x *FontDialogButton) UpdateNextAccessibleSibling(NewSiblingVar Accessible) {

	XGtkAccessibleUpdateNextAccessibleSibling(x.GoPointer(), NewSiblingVar.GoPointer())

}

// Informs ATs that the platform state has changed.
//
// This function should be used by `GtkAccessible` implementations that
// have a platform state but are not widgets. Widgets handle platform
// states automatically.
func (x *FontDialogButton) UpdatePlatformState(StateVar AccessiblePlatformState) {

	XGtkAccessibleUpdatePlatformState(x.GoPointer(), StateVar)

}

// Updates a list of accessible properties.
//
// See the [enum@Gtk.AccessibleProperty] documentation for the
// value types of accessible properties.
//
// This function should be called by `GtkWidget` types whenever
// an accessible property change must be communicated to assistive
// technologies.
//
// Example:
// ```c
// value = gtk_adjustment_get_value (adjustment);
// gtk_accessible_update_property (GTK_ACCESSIBLE (spin_button),
//
//	GTK_ACCESSIBLE_PROPERTY_VALUE_NOW, value,
//	-1);
//
// ```
func (x *FontDialogButton) UpdateProperty(FirstPropertyVar AccessibleProperty, varArgs ...interface{}) {

	XGtkAccessibleUpdateProperty(x.GoPointer(), FirstPropertyVar, varArgs...)

}

// Updates an array of accessible properties.
//
// This function should be called by `GtkWidget` types whenever an accessible
// property change must be communicated to assistive technologies.
//
// This function is meant to be used by language bindings.
func (x *FontDialogButton) UpdatePropertyValue(NPropertiesVar int, PropertiesVar []AccessibleProperty, ValuesVar []gobject.Value) {

	XGtkAccessibleUpdatePropertyValue(x.GoPointer(), NPropertiesVar, PropertiesVar, ValuesVar)

}

// Updates a list of accessible relations.
//
// This function should be called by `GtkWidget` types whenever an accessible
// relation change must be communicated to assistive technologies.
//
// If the [enum@Gtk.AccessibleRelation] requires a list of references,
// you should pass each reference individually, followed by `NULL`, e.g.
//
// ```c
// gtk_accessible_update_relation (accessible,
//
//	GTK_ACCESSIBLE_RELATION_CONTROLS,
//	  ref1, NULL,
//	GTK_ACCESSIBLE_RELATION_LABELLED_BY,
//	  ref1, ref2, ref3, NULL,
//	-1);
//
// ```
func (x *FontDialogButton) UpdateRelation(FirstRelationVar AccessibleRelation, varArgs ...interface{}) {

	XGtkAccessibleUpdateRelation(x.GoPointer(), FirstRelationVar, varArgs...)

}

// Updates an array of accessible relations.
//
// This function should be called by `GtkWidget` types whenever an accessible
// relation change must be communicated to assistive technologies.
//
// This function is meant to be used by language bindings.
func (x *FontDialogButton) UpdateRelationValue(NRelationsVar int, RelationsVar []AccessibleRelation, ValuesVar []gobject.Value) {

	XGtkAccessibleUpdateRelationValue(x.GoPointer(), NRelationsVar, RelationsVar, ValuesVar)

}

// Updates a list of accessible states.
//
// See the [enum@Gtk.AccessibleState] documentation for the
// value types of accessible states.
//
// This function should be called by `GtkWidget` types whenever
// an accessible state change must be communicated to assistive
// technologies.
//
// Example:
//
// ```c
// value = GTK_ACCESSIBLE_TRISTATE_MIXED;
// gtk_accessible_update_state (GTK_ACCESSIBLE (check_button),
//
//	GTK_ACCESSIBLE_STATE_CHECKED, value,
//	-1);
//
// ```
func (x *FontDialogButton) UpdateState(FirstStateVar AccessibleState, varArgs ...interface{}) {

	XGtkAccessibleUpdateState(x.GoPointer(), FirstStateVar, varArgs...)

}

// Updates an array of accessible states.
//
// This function should be called by `GtkWidget` types whenever an accessible
// state change must be communicated to assistive technologies.
//
// This function is meant to be used by language bindings.
func (x *FontDialogButton) UpdateStateValue(NStatesVar int, StatesVar []AccessibleState, ValuesVar []gobject.Value) {

	XGtkAccessibleUpdateStateValue(x.GoPointer(), NStatesVar, StatesVar, ValuesVar)

}

// Gets the ID of the @buildable object.
//
// `GtkBuilder` sets the name based on the ID attribute
// of the `&lt;object&gt;` tag used to construct the @buildable.
func (x *FontDialogButton) GetBuildableId() string {

	cret := XGtkBuildableGetBuildableId(x.GoPointer())
	return cret
}

func init() {
	lib, err := purego.Dlopen(core.GetPath("GTK"), purego.RTLD_NOW|purego.RTLD_GLOBAL)
	if err != nil {
		panic(err)
	}

	core.PuregoSafeRegister(&xFontLevelGLibType, lib, "gtk_font_level_get_type")

	core.PuregoSafeRegister(&xFontDialogButtonGLibType, lib, "gtk_font_dialog_button_get_type")

	core.PuregoSafeRegister(&xNewFontDialogButton, lib, "gtk_font_dialog_button_new")

	core.PuregoSafeRegister(&xFontDialogButtonGetDialog, lib, "gtk_font_dialog_button_get_dialog")
	core.PuregoSafeRegister(&xFontDialogButtonGetFontDesc, lib, "gtk_font_dialog_button_get_font_desc")
	core.PuregoSafeRegister(&xFontDialogButtonGetFontFeatures, lib, "gtk_font_dialog_button_get_font_features")
	core.PuregoSafeRegister(&xFontDialogButtonGetLanguage, lib, "gtk_font_dialog_button_get_language")
	core.PuregoSafeRegister(&xFontDialogButtonGetLevel, lib, "gtk_font_dialog_button_get_level")
	core.PuregoSafeRegister(&xFontDialogButtonGetUseFont, lib, "gtk_font_dialog_button_get_use_font")
	core.PuregoSafeRegister(&xFontDialogButtonGetUseSize, lib, "gtk_font_dialog_button_get_use_size")
	core.PuregoSafeRegister(&xFontDialogButtonSetDialog, lib, "gtk_font_dialog_button_set_dialog")
	core.PuregoSafeRegister(&xFontDialogButtonSetFontDesc, lib, "gtk_font_dialog_button_set_font_desc")
	core.PuregoSafeRegister(&xFontDialogButtonSetFontFeatures, lib, "gtk_font_dialog_button_set_font_features")
	core.PuregoSafeRegister(&xFontDialogButtonSetLanguage, lib, "gtk_font_dialog_button_set_language")
	core.PuregoSafeRegister(&xFontDialogButtonSetLevel, lib, "gtk_font_dialog_button_set_level")
	core.PuregoSafeRegister(&xFontDialogButtonSetUseFont, lib, "gtk_font_dialog_button_set_use_font")
	core.PuregoSafeRegister(&xFontDialogButtonSetUseSize, lib, "gtk_font_dialog_button_set_use_size")

}
