// Package gtk was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package gtk

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/internal/core"
	"github.com/jwijenbergh/puregotk/v4/gio"
	"github.com/jwijenbergh/puregotk/v4/glib"
	"github.com/jwijenbergh/puregotk/v4/gobject"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type PrintDialogClass struct {
	_ structs.HostLayout

	ParentClass uintptr
}

func (x *PrintDialogClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

// An auxiliary object for printing that allows decoupling the setup from the printing.
//
// A print setup is obtained by calling [method@Gtk.PrintDialog.setup],
// and can later be passed to print functions such as [method@Gtk.PrintDialog.print].
//
// Print setups can be reused for multiple print calls.
//
// Applications may wish to store the page_setup and print_settings from the print setup
// and copy them to the PrintDialog if they want to keep using them.
type PrintSetup struct {
	_ structs.HostLayout
}

var xPrintSetupGLibType func() types.GType

func PrintSetupGLibType() types.GType {
	return xPrintSetupGLibType()
}

func (x *PrintSetup) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

var xPrintSetupGetPageSetup func(uintptr) uintptr

// Returns the page setup of @setup.
//
// It may be different from the `GtkPrintDialog`'s page setup
// if the user changed it during the setup process.
func (x *PrintSetup) GetPageSetup() *PageSetup {
	var cls *PageSetup

	cret := xPrintSetupGetPageSetup(x.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &PageSetup{}
	cls.Ptr = cret
	return cls
}

var xPrintSetupGetPrintSettings func(uintptr) uintptr

// Returns the print settings of @setup.
//
// They may be different from the `GtkPrintDialog`'s settings
// if the user changed them during the setup process.
func (x *PrintSetup) GetPrintSettings() *PrintSettings {
	var cls *PrintSettings

	cret := xPrintSetupGetPrintSettings(x.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &PrintSettings{}
	cls.Ptr = cret
	return cls
}

var xPrintSetupRef func(uintptr) *PrintSetup

// Increase the reference count of @setup.
func (x *PrintSetup) Ref() *PrintSetup {

	cret := xPrintSetupRef(x.GoPointer())
	return cret
}

var xPrintSetupUnref func(uintptr)

// Decrease the reference count of @setup.
//
// If the reference count reaches zero,
// the object is freed.
func (x *PrintSetup) Unref() {

	xPrintSetupUnref(x.GoPointer())

}

// Asynchronous API to present a print dialog to the user.
//
// `GtkPrintDialog` collects the arguments that are needed to present
//
//	the dialog, such as a title for the dialog and whether it should
//	be modal.
//
// The dialog is shown with the [method@Gtk.PrintDialog.setup] function.
//
// The actual printing can be done with [method@Gtk.PrintDialog.print] or
// [method@Gtk.PrintDialog.print_file]. These APIs follows the GIO async pattern,
// and the results can be obtained by calling the corresponding finish methods.
type PrintDialog struct {
	gobject.Object
}

var xPrintDialogGLibType func() types.GType

func PrintDialogGLibType() types.GType {
	return xPrintDialogGLibType()
}

func PrintDialogNewFromInternalPtr(ptr uintptr) *PrintDialog {
	cls := &PrintDialog{}
	cls.Ptr = ptr
	return cls
}

var xNewPrintDialog func() uintptr

// Creates a new `GtkPrintDialog` object.
func NewPrintDialog() *PrintDialog {
	var cls *PrintDialog

	cret := xNewPrintDialog()

	if cret == 0 {
		return nil
	}
	cls = &PrintDialog{}
	cls.Ptr = cret
	return cls
}

var xPrintDialogGetAcceptLabel func(uintptr) string

// Returns the label that will be shown on the
// accept button of the print dialog.
func (x *PrintDialog) GetAcceptLabel() string {

	cret := xPrintDialogGetAcceptLabel(x.GoPointer())
	return cret
}

var xPrintDialogGetModal func(uintptr) bool

// Returns whether the print dialog blocks
// interaction with the parent window while
// it is presented.
func (x *PrintDialog) GetModal() bool {

	cret := xPrintDialogGetModal(x.GoPointer())
	return cret
}

var xPrintDialogGetPageSetup func(uintptr) uintptr

// Returns the page setup.
func (x *PrintDialog) GetPageSetup() *PageSetup {
	var cls *PageSetup

	cret := xPrintDialogGetPageSetup(x.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &PageSetup{}
	cls.Ptr = cret
	return cls
}

var xPrintDialogGetPrintSettings func(uintptr) uintptr

// Returns the print settings for the print dialog.
func (x *PrintDialog) GetPrintSettings() *PrintSettings {
	var cls *PrintSettings

	cret := xPrintDialogGetPrintSettings(x.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &PrintSettings{}
	cls.Ptr = cret
	return cls
}

var xPrintDialogGetTitle func(uintptr) string

// Returns the title that will be shown on the
// print dialog.
func (x *PrintDialog) GetTitle() string {

	cret := xPrintDialogGetTitle(x.GoPointer())
	return cret
}

var xPrintDialogPrint func(uintptr, uintptr, *PrintSetup, uintptr, uintptr, uintptr)

// This function prints content from a stream.
//
// If you pass `NULL` as @setup, then this method will present a print dialog.
// Otherwise, it will attempt to print directly, without user interaction.
//
// The @callback will be called when the printing is done.
func (x *PrintDialog) Print(ParentVar *Window, SetupVar *PrintSetup, CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {

	xPrintDialogPrint(x.GoPointer(), ParentVar.GoPointer(), SetupVar, CancellableVar.GoPointer(), glib.NewCallback(CallbackVar), UserDataVar)

}

var xPrintDialogPrintFile func(uintptr, uintptr, *PrintSetup, uintptr, uintptr, uintptr, uintptr)

// This function prints a file.
//
// If you pass `NULL` as @setup, then this method will present a print dialog.
// Otherwise, it will attempt to print directly, without user interaction.
func (x *PrintDialog) PrintFile(ParentVar *Window, SetupVar *PrintSetup, FileVar gio.File, CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {

	xPrintDialogPrintFile(x.GoPointer(), ParentVar.GoPointer(), SetupVar, FileVar.GoPointer(), CancellableVar.GoPointer(), glib.NewCallback(CallbackVar), UserDataVar)

}

var xPrintDialogPrintFileFinish func(uintptr, uintptr, **glib.Error) bool

// Finishes the [method@Gtk.PrintDialog.print_file] call and
// returns the results.
func (x *PrintDialog) PrintFileFinish(ResultVar gio.AsyncResult) (bool, error) {
	var cerr *glib.Error

	cret := xPrintDialogPrintFileFinish(x.GoPointer(), ResultVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

var xPrintDialogPrintFinish func(uintptr, uintptr, **glib.Error) uintptr

// Finishes the [method@Gtk.PrintDialog.print] call and
// returns the results.
//
// If the call was successful, the content to be printed should be
// written to the returned output stream. Otherwise, `NULL` is returned.
//
// The overall results of the print operation will be returned in the
// [method@Gio.OutputStream.close] call, so if you are interested in the
// results, you need to explicitly close the output stream (it will be
// closed automatically if you just unref it). Be aware that the close
// call may not be instant as it operation will for the printer to finish
// printing.
func (x *PrintDialog) PrintFinish(ResultVar gio.AsyncResult) (*gio.OutputStream, error) {
	var cls *gio.OutputStream
	var cerr *glib.Error

	cret := xPrintDialogPrintFinish(x.GoPointer(), ResultVar.GoPointer(), &cerr)

	if cret == 0 {
		return nil, cerr
	}
	cls = &gio.OutputStream{}
	cls.Ptr = cret
	if cerr == nil {
		return cls, nil
	}
	return cls, cerr

}

var xPrintDialogSetAcceptLabel func(uintptr, string)

// Sets the label that will be shown on the
// accept button of the print dialog shown for
// [method@Gtk.PrintDialog.setup].
func (x *PrintDialog) SetAcceptLabel(AcceptLabelVar string) {

	xPrintDialogSetAcceptLabel(x.GoPointer(), AcceptLabelVar)

}

var xPrintDialogSetModal func(uintptr, bool)

// Sets whether the print dialog blocks
// interaction with the parent window while
// it is presented.
func (x *PrintDialog) SetModal(ModalVar bool) {

	xPrintDialogSetModal(x.GoPointer(), ModalVar)

}

var xPrintDialogSetPageSetup func(uintptr, uintptr)

// Set the page setup for the print dialog.
func (x *PrintDialog) SetPageSetup(PageSetupVar *PageSetup) {

	xPrintDialogSetPageSetup(x.GoPointer(), PageSetupVar.GoPointer())

}

var xPrintDialogSetPrintSettings func(uintptr, uintptr)

// Sets the print settings for the print dialog.
func (x *PrintDialog) SetPrintSettings(PrintSettingsVar *PrintSettings) {

	xPrintDialogSetPrintSettings(x.GoPointer(), PrintSettingsVar.GoPointer())

}

var xPrintDialogSetTitle func(uintptr, string)

// Sets the title that will be shown on the print dialog.
func (x *PrintDialog) SetTitle(TitleVar string) {

	xPrintDialogSetTitle(x.GoPointer(), TitleVar)

}

var xPrintDialogSetup func(uintptr, uintptr, uintptr, uintptr, uintptr)

// This function presents a print dialog to let the user select a printer,
// and set up print settings and page setup.
//
// The @callback will be called when the dialog is dismissed.
// The obtained [struct@Gtk.PrintSetup] can then be passed
// to [method@Gtk.PrintDialog.print] or [method@Gtk.PrintDialog.print_file].
//
// One possible use for this method is to have the user select a printer,
// then show a page setup UI in the application (e.g. to arrange images
// on a page), then call [method@Gtk.PrintDialog.print] on @self
// to do the printing without further user interaction.
func (x *PrintDialog) Setup(ParentVar *Window, CancellableVar *gio.Cancellable, CallbackVar *gio.AsyncReadyCallback, UserDataVar uintptr) {

	xPrintDialogSetup(x.GoPointer(), ParentVar.GoPointer(), CancellableVar.GoPointer(), glib.NewCallback(CallbackVar), UserDataVar)

}

var xPrintDialogSetupFinish func(uintptr, uintptr, **glib.Error) *PrintSetup

// Finishes the [method@Gtk.PrintDialog.setup] call.
//
// If the call was successful, it returns a [struct@Gtk.PrintSetup]
// which contains the print settings and page setup information that
// will be used to print.
func (x *PrintDialog) SetupFinish(ResultVar gio.AsyncResult) (*PrintSetup, error) {
	var cerr *glib.Error

	cret := xPrintDialogSetupFinish(x.GoPointer(), ResultVar.GoPointer(), &cerr)
	if cerr == nil {
		return cret, nil
	}
	return cret, cerr

}

func (c *PrintDialog) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *PrintDialog) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	lib, err := purego.Dlopen(core.GetPath("GTK"), purego.RTLD_NOW|purego.RTLD_GLOBAL)
	if err != nil {
		panic(err)
	}

	core.PuregoSafeRegister(&xPrintSetupGLibType, lib, "gtk_print_setup_get_type")

	core.PuregoSafeRegister(&xPrintSetupGetPageSetup, lib, "gtk_print_setup_get_page_setup")
	core.PuregoSafeRegister(&xPrintSetupGetPrintSettings, lib, "gtk_print_setup_get_print_settings")
	core.PuregoSafeRegister(&xPrintSetupRef, lib, "gtk_print_setup_ref")
	core.PuregoSafeRegister(&xPrintSetupUnref, lib, "gtk_print_setup_unref")

	core.PuregoSafeRegister(&xPrintDialogGLibType, lib, "gtk_print_dialog_get_type")

	core.PuregoSafeRegister(&xNewPrintDialog, lib, "gtk_print_dialog_new")

	core.PuregoSafeRegister(&xPrintDialogGetAcceptLabel, lib, "gtk_print_dialog_get_accept_label")
	core.PuregoSafeRegister(&xPrintDialogGetModal, lib, "gtk_print_dialog_get_modal")
	core.PuregoSafeRegister(&xPrintDialogGetPageSetup, lib, "gtk_print_dialog_get_page_setup")
	core.PuregoSafeRegister(&xPrintDialogGetPrintSettings, lib, "gtk_print_dialog_get_print_settings")
	core.PuregoSafeRegister(&xPrintDialogGetTitle, lib, "gtk_print_dialog_get_title")
	core.PuregoSafeRegister(&xPrintDialogPrint, lib, "gtk_print_dialog_print")
	core.PuregoSafeRegister(&xPrintDialogPrintFile, lib, "gtk_print_dialog_print_file")
	core.PuregoSafeRegister(&xPrintDialogPrintFileFinish, lib, "gtk_print_dialog_print_file_finish")
	core.PuregoSafeRegister(&xPrintDialogPrintFinish, lib, "gtk_print_dialog_print_finish")
	core.PuregoSafeRegister(&xPrintDialogSetAcceptLabel, lib, "gtk_print_dialog_set_accept_label")
	core.PuregoSafeRegister(&xPrintDialogSetModal, lib, "gtk_print_dialog_set_modal")
	core.PuregoSafeRegister(&xPrintDialogSetPageSetup, lib, "gtk_print_dialog_set_page_setup")
	core.PuregoSafeRegister(&xPrintDialogSetPrintSettings, lib, "gtk_print_dialog_set_print_settings")
	core.PuregoSafeRegister(&xPrintDialogSetTitle, lib, "gtk_print_dialog_set_title")
	core.PuregoSafeRegister(&xPrintDialogSetup, lib, "gtk_print_dialog_setup")
	core.PuregoSafeRegister(&xPrintDialogSetupFinish, lib, "gtk_print_dialog_setup_finish")

}
