// Package gobject was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package gobject

import (
	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/internal/core"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

// A numerical value which represents the unique identifier of a registered
// type.
type Type = types.GType

var xVariantGetGtype func() types.GType

func VariantGetGtype() types.GType {

	cret := xVariantGetGtype()
	return cret
}

func init() {
	lib, err := purego.Dlopen(core.GetPath("GOBJECT"), purego.RTLD_NOW|purego.RTLD_GLOBAL)
	if err != nil {
		panic(err)
	}

	core.PuregoSafeRegister(&xVariantGetGtype, lib, "g_variant_get_gtype")

}
