// Package gobject was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package gobject

import (
	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/internal/core"
)

var xCclosureMarshalBOOLEANBOXEDBOXED func(*Closure, *Value, uint, *Value, uintptr, uintptr)

// A #GClosureMarshal function for use with signals with handlers that
// take two boxed pointers as arguments and return a boolean.  If you
// have such a signal, you will probably also need to use an
// accumulator, such as g_signal_accumulator_true_handled().
func CclosureMarshalBOOLEANBOXEDBOXED(ClosureVar *Closure, ReturnValueVar *Value, NParamValuesVar uint, ParamValuesVar *Value, InvocationHintVar uintptr, MarshalDataVar uintptr) {

	xCclosureMarshalBOOLEANBOXEDBOXED(ClosureVar, ReturnValueVar, NParamValuesVar, ParamValuesVar, InvocationHintVar, MarshalDataVar)

}

var xCclosureMarshalBOOLEANFLAGS func(*Closure, *Value, uint, *Value, uintptr, uintptr)

// A #GClosureMarshal function for use with signals with handlers that
// take a flags type as an argument and return a boolean.  If you have
// such a signal, you will probably also need to use an accumulator,
// such as g_signal_accumulator_true_handled().
func CclosureMarshalBOOLEANFLAGS(ClosureVar *Closure, ReturnValueVar *Value, NParamValuesVar uint, ParamValuesVar *Value, InvocationHintVar uintptr, MarshalDataVar uintptr) {

	xCclosureMarshalBOOLEANFLAGS(ClosureVar, ReturnValueVar, NParamValuesVar, ParamValuesVar, InvocationHintVar, MarshalDataVar)

}

var xCclosureMarshalSTRINGOBJECTPOINTER func(*Closure, *Value, uint, *Value, uintptr, uintptr)

// A #GClosureMarshal function for use with signals with handlers that
// take a #GObject and a pointer and produce a string.  It is highly
// unlikely that your signal handler fits this description.
func CclosureMarshalSTRINGOBJECTPOINTER(ClosureVar *Closure, ReturnValueVar *Value, NParamValuesVar uint, ParamValuesVar *Value, InvocationHintVar uintptr, MarshalDataVar uintptr) {

	xCclosureMarshalSTRINGOBJECTPOINTER(ClosureVar, ReturnValueVar, NParamValuesVar, ParamValuesVar, InvocationHintVar, MarshalDataVar)

}

var xCclosureMarshalVOIDBOOLEAN func(*Closure, *Value, uint, *Value, uintptr, uintptr)

// A #GClosureMarshal function for use with signals with a single
// boolean argument.
func CclosureMarshalVOIDBOOLEAN(ClosureVar *Closure, ReturnValueVar *Value, NParamValuesVar uint, ParamValuesVar *Value, InvocationHintVar uintptr, MarshalDataVar uintptr) {

	xCclosureMarshalVOIDBOOLEAN(ClosureVar, ReturnValueVar, NParamValuesVar, ParamValuesVar, InvocationHintVar, MarshalDataVar)

}

var xCclosureMarshalVOIDBOXED func(*Closure, *Value, uint, *Value, uintptr, uintptr)

// A #GClosureMarshal function for use with signals with a single
// argument which is any boxed pointer type.
func CclosureMarshalVOIDBOXED(ClosureVar *Closure, ReturnValueVar *Value, NParamValuesVar uint, ParamValuesVar *Value, InvocationHintVar uintptr, MarshalDataVar uintptr) {

	xCclosureMarshalVOIDBOXED(ClosureVar, ReturnValueVar, NParamValuesVar, ParamValuesVar, InvocationHintVar, MarshalDataVar)

}

var xCclosureMarshalVOIDCHAR func(*Closure, *Value, uint, *Value, uintptr, uintptr)

// A #GClosureMarshal function for use with signals with a single
// character argument.
func CclosureMarshalVOIDCHAR(ClosureVar *Closure, ReturnValueVar *Value, NParamValuesVar uint, ParamValuesVar *Value, InvocationHintVar uintptr, MarshalDataVar uintptr) {

	xCclosureMarshalVOIDCHAR(ClosureVar, ReturnValueVar, NParamValuesVar, ParamValuesVar, InvocationHintVar, MarshalDataVar)

}

var xCclosureMarshalVOIDDOUBLE func(*Closure, *Value, uint, *Value, uintptr, uintptr)

// A #GClosureMarshal function for use with signals with one
// double-precision floating point argument.
func CclosureMarshalVOIDDOUBLE(ClosureVar *Closure, ReturnValueVar *Value, NParamValuesVar uint, ParamValuesVar *Value, InvocationHintVar uintptr, MarshalDataVar uintptr) {

	xCclosureMarshalVOIDDOUBLE(ClosureVar, ReturnValueVar, NParamValuesVar, ParamValuesVar, InvocationHintVar, MarshalDataVar)

}

var xCclosureMarshalVOIDENUM func(*Closure, *Value, uint, *Value, uintptr, uintptr)

// A #GClosureMarshal function for use with signals with a single
// argument with an enumerated type.
func CclosureMarshalVOIDENUM(ClosureVar *Closure, ReturnValueVar *Value, NParamValuesVar uint, ParamValuesVar *Value, InvocationHintVar uintptr, MarshalDataVar uintptr) {

	xCclosureMarshalVOIDENUM(ClosureVar, ReturnValueVar, NParamValuesVar, ParamValuesVar, InvocationHintVar, MarshalDataVar)

}

var xCclosureMarshalVOIDFLAGS func(*Closure, *Value, uint, *Value, uintptr, uintptr)

// A #GClosureMarshal function for use with signals with a single
// argument with a flags types.
func CclosureMarshalVOIDFLAGS(ClosureVar *Closure, ReturnValueVar *Value, NParamValuesVar uint, ParamValuesVar *Value, InvocationHintVar uintptr, MarshalDataVar uintptr) {

	xCclosureMarshalVOIDFLAGS(ClosureVar, ReturnValueVar, NParamValuesVar, ParamValuesVar, InvocationHintVar, MarshalDataVar)

}

var xCclosureMarshalVOIDFLOAT func(*Closure, *Value, uint, *Value, uintptr, uintptr)

// A #GClosureMarshal function for use with signals with one
// single-precision floating point argument.
func CclosureMarshalVOIDFLOAT(ClosureVar *Closure, ReturnValueVar *Value, NParamValuesVar uint, ParamValuesVar *Value, InvocationHintVar uintptr, MarshalDataVar uintptr) {

	xCclosureMarshalVOIDFLOAT(ClosureVar, ReturnValueVar, NParamValuesVar, ParamValuesVar, InvocationHintVar, MarshalDataVar)

}

var xCclosureMarshalVOIDINT func(*Closure, *Value, uint, *Value, uintptr, uintptr)

// A #GClosureMarshal function for use with signals with a single
// integer argument.
func CclosureMarshalVOIDINT(ClosureVar *Closure, ReturnValueVar *Value, NParamValuesVar uint, ParamValuesVar *Value, InvocationHintVar uintptr, MarshalDataVar uintptr) {

	xCclosureMarshalVOIDINT(ClosureVar, ReturnValueVar, NParamValuesVar, ParamValuesVar, InvocationHintVar, MarshalDataVar)

}

var xCclosureMarshalVOIDLONG func(*Closure, *Value, uint, *Value, uintptr, uintptr)

// A #GClosureMarshal function for use with signals with with a single
// long integer argument.
func CclosureMarshalVOIDLONG(ClosureVar *Closure, ReturnValueVar *Value, NParamValuesVar uint, ParamValuesVar *Value, InvocationHintVar uintptr, MarshalDataVar uintptr) {

	xCclosureMarshalVOIDLONG(ClosureVar, ReturnValueVar, NParamValuesVar, ParamValuesVar, InvocationHintVar, MarshalDataVar)

}

var xCclosureMarshalVOIDOBJECT func(*Closure, *Value, uint, *Value, uintptr, uintptr)

// A #GClosureMarshal function for use with signals with a single
// #GObject argument.
func CclosureMarshalVOIDOBJECT(ClosureVar *Closure, ReturnValueVar *Value, NParamValuesVar uint, ParamValuesVar *Value, InvocationHintVar uintptr, MarshalDataVar uintptr) {

	xCclosureMarshalVOIDOBJECT(ClosureVar, ReturnValueVar, NParamValuesVar, ParamValuesVar, InvocationHintVar, MarshalDataVar)

}

var xCclosureMarshalVOIDPARAM func(*Closure, *Value, uint, *Value, uintptr, uintptr)

// A #GClosureMarshal function for use with signals with a single
// argument of type #GParamSpec.
func CclosureMarshalVOIDPARAM(ClosureVar *Closure, ReturnValueVar *Value, NParamValuesVar uint, ParamValuesVar *Value, InvocationHintVar uintptr, MarshalDataVar uintptr) {

	xCclosureMarshalVOIDPARAM(ClosureVar, ReturnValueVar, NParamValuesVar, ParamValuesVar, InvocationHintVar, MarshalDataVar)

}

var xCclosureMarshalVOIDPOINTER func(*Closure, *Value, uint, *Value, uintptr, uintptr)

// A #GClosureMarshal function for use with signals with a single raw
// pointer argument type.
//
// If it is possible, it is better to use one of the more specific
// functions such as g_cclosure_marshal_VOID__OBJECT() or
// g_cclosure_marshal_VOID__OBJECT().
func CclosureMarshalVOIDPOINTER(ClosureVar *Closure, ReturnValueVar *Value, NParamValuesVar uint, ParamValuesVar *Value, InvocationHintVar uintptr, MarshalDataVar uintptr) {

	xCclosureMarshalVOIDPOINTER(ClosureVar, ReturnValueVar, NParamValuesVar, ParamValuesVar, InvocationHintVar, MarshalDataVar)

}

var xCclosureMarshalVOIDSTRING func(*Closure, *Value, uint, *Value, uintptr, uintptr)

// A #GClosureMarshal function for use with signals with a single string
// argument.
func CclosureMarshalVOIDSTRING(ClosureVar *Closure, ReturnValueVar *Value, NParamValuesVar uint, ParamValuesVar *Value, InvocationHintVar uintptr, MarshalDataVar uintptr) {

	xCclosureMarshalVOIDSTRING(ClosureVar, ReturnValueVar, NParamValuesVar, ParamValuesVar, InvocationHintVar, MarshalDataVar)

}

var xCclosureMarshalVOIDUCHAR func(*Closure, *Value, uint, *Value, uintptr, uintptr)

// A #GClosureMarshal function for use with signals with a single
// unsigned character argument.
func CclosureMarshalVOIDUCHAR(ClosureVar *Closure, ReturnValueVar *Value, NParamValuesVar uint, ParamValuesVar *Value, InvocationHintVar uintptr, MarshalDataVar uintptr) {

	xCclosureMarshalVOIDUCHAR(ClosureVar, ReturnValueVar, NParamValuesVar, ParamValuesVar, InvocationHintVar, MarshalDataVar)

}

var xCclosureMarshalVOIDUINT func(*Closure, *Value, uint, *Value, uintptr, uintptr)

// A #GClosureMarshal function for use with signals with with a single
// unsigned integer argument.
func CclosureMarshalVOIDUINT(ClosureVar *Closure, ReturnValueVar *Value, NParamValuesVar uint, ParamValuesVar *Value, InvocationHintVar uintptr, MarshalDataVar uintptr) {

	xCclosureMarshalVOIDUINT(ClosureVar, ReturnValueVar, NParamValuesVar, ParamValuesVar, InvocationHintVar, MarshalDataVar)

}

var xCclosureMarshalVOIDUINTPOINTER func(*Closure, *Value, uint, *Value, uintptr, uintptr)

// A #GClosureMarshal function for use with signals with an unsigned int
// and a pointer as arguments.
func CclosureMarshalVOIDUINTPOINTER(ClosureVar *Closure, ReturnValueVar *Value, NParamValuesVar uint, ParamValuesVar *Value, InvocationHintVar uintptr, MarshalDataVar uintptr) {

	xCclosureMarshalVOIDUINTPOINTER(ClosureVar, ReturnValueVar, NParamValuesVar, ParamValuesVar, InvocationHintVar, MarshalDataVar)

}

var xCclosureMarshalVOIDULONG func(*Closure, *Value, uint, *Value, uintptr, uintptr)

// A #GClosureMarshal function for use with signals with a single
// unsigned long integer argument.
func CclosureMarshalVOIDULONG(ClosureVar *Closure, ReturnValueVar *Value, NParamValuesVar uint, ParamValuesVar *Value, InvocationHintVar uintptr, MarshalDataVar uintptr) {

	xCclosureMarshalVOIDULONG(ClosureVar, ReturnValueVar, NParamValuesVar, ParamValuesVar, InvocationHintVar, MarshalDataVar)

}

var xCclosureMarshalVOIDVARIANT func(*Closure, *Value, uint, *Value, uintptr, uintptr)

// A #GClosureMarshal function for use with signals with a single
// #GVariant argument.
func CclosureMarshalVOIDVARIANT(ClosureVar *Closure, ReturnValueVar *Value, NParamValuesVar uint, ParamValuesVar *Value, InvocationHintVar uintptr, MarshalDataVar uintptr) {

	xCclosureMarshalVOIDVARIANT(ClosureVar, ReturnValueVar, NParamValuesVar, ParamValuesVar, InvocationHintVar, MarshalDataVar)

}

var xCclosureMarshalVOIDVOID func(*Closure, *Value, uint, *Value, uintptr, uintptr)

// A #GClosureMarshal function for use with signals with no arguments.
func CclosureMarshalVOIDVOID(ClosureVar *Closure, ReturnValueVar *Value, NParamValuesVar uint, ParamValuesVar *Value, InvocationHintVar uintptr, MarshalDataVar uintptr) {

	xCclosureMarshalVOIDVOID(ClosureVar, ReturnValueVar, NParamValuesVar, ParamValuesVar, InvocationHintVar, MarshalDataVar)

}

func init() {
	lib, err := purego.Dlopen(core.GetPath("GOBJECT"), purego.RTLD_NOW|purego.RTLD_GLOBAL)
	if err != nil {
		panic(err)
	}

	core.PuregoSafeRegister(&xCclosureMarshalBOOLEANBOXEDBOXED, lib, "g_cclosure_marshal_BOOLEAN__BOXED_BOXED")
	core.PuregoSafeRegister(&xCclosureMarshalBOOLEANFLAGS, lib, "g_cclosure_marshal_BOOLEAN__FLAGS")
	core.PuregoSafeRegister(&xCclosureMarshalSTRINGOBJECTPOINTER, lib, "g_cclosure_marshal_STRING__OBJECT_POINTER")
	core.PuregoSafeRegister(&xCclosureMarshalVOIDBOOLEAN, lib, "g_cclosure_marshal_VOID__BOOLEAN")
	core.PuregoSafeRegister(&xCclosureMarshalVOIDBOXED, lib, "g_cclosure_marshal_VOID__BOXED")
	core.PuregoSafeRegister(&xCclosureMarshalVOIDCHAR, lib, "g_cclosure_marshal_VOID__CHAR")
	core.PuregoSafeRegister(&xCclosureMarshalVOIDDOUBLE, lib, "g_cclosure_marshal_VOID__DOUBLE")
	core.PuregoSafeRegister(&xCclosureMarshalVOIDENUM, lib, "g_cclosure_marshal_VOID__ENUM")
	core.PuregoSafeRegister(&xCclosureMarshalVOIDFLAGS, lib, "g_cclosure_marshal_VOID__FLAGS")
	core.PuregoSafeRegister(&xCclosureMarshalVOIDFLOAT, lib, "g_cclosure_marshal_VOID__FLOAT")
	core.PuregoSafeRegister(&xCclosureMarshalVOIDINT, lib, "g_cclosure_marshal_VOID__INT")
	core.PuregoSafeRegister(&xCclosureMarshalVOIDLONG, lib, "g_cclosure_marshal_VOID__LONG")
	core.PuregoSafeRegister(&xCclosureMarshalVOIDOBJECT, lib, "g_cclosure_marshal_VOID__OBJECT")
	core.PuregoSafeRegister(&xCclosureMarshalVOIDPARAM, lib, "g_cclosure_marshal_VOID__PARAM")
	core.PuregoSafeRegister(&xCclosureMarshalVOIDPOINTER, lib, "g_cclosure_marshal_VOID__POINTER")
	core.PuregoSafeRegister(&xCclosureMarshalVOIDSTRING, lib, "g_cclosure_marshal_VOID__STRING")
	core.PuregoSafeRegister(&xCclosureMarshalVOIDUCHAR, lib, "g_cclosure_marshal_VOID__UCHAR")
	core.PuregoSafeRegister(&xCclosureMarshalVOIDUINT, lib, "g_cclosure_marshal_VOID__UINT")
	core.PuregoSafeRegister(&xCclosureMarshalVOIDUINTPOINTER, lib, "g_cclosure_marshal_VOID__UINT_POINTER")
	core.PuregoSafeRegister(&xCclosureMarshalVOIDULONG, lib, "g_cclosure_marshal_VOID__ULONG")
	core.PuregoSafeRegister(&xCclosureMarshalVOIDVARIANT, lib, "g_cclosure_marshal_VOID__VARIANT")
	core.PuregoSafeRegister(&xCclosureMarshalVOIDVOID, lib, "g_cclosure_marshal_VOID__VOID")

}
