// Package gobject was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package gobject

import "github.com/jwijenbergh/puregotk/v4/gobject/types"

type ValueDataUnion = uintptr

type IOCondition int

var xIOConditionGLibType func() types.GType

func IOConditionGLibType() types.GType {
	return xIOConditionGLibType()
}

const (
	GIoInValue IOCondition = 1

	GIoOutValue IOCondition = 4

	GIoPriValue IOCondition = 2

	GIoErrValue IOCondition = 8

	GIoHupValue IOCondition = 16

	GIoNvalValue IOCondition = 32
)
