// Package glib was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package glib

// A type which is used to hold a process identification.
//
// On UNIX, processes are identified by a process id (an integer),
// while Windows uses process handles (which are pointers).
//
// GPid is used in GLib only for descendant processes spawned with
// the g_spawn functions.
type Pid = int

const (
	// The directory separator character.
	//
	// This is `'/'` on UNIX machines and `'\'` under Windows.
	DIR_SEPARATOR int = 47
	// The directory separator as a string.
	//
	// This is `"/"` on UNIX machines and `"\"` under Windows.
	DIR_SEPARATOR_S string = "/"

	GINT16_FORMAT string = "hi"

	GINT16_MODIFIER string = "h"

	GINT32_FORMAT string = "i"

	GINT32_MODIFIER string = ""

	GINT64_FORMAT string = "li"

	GINT64_MODIFIER string = "l"

	GINTPTR_FORMAT string = "li"

	GINTPTR_MODIFIER string = "l"

	GSIZE_FORMAT string = "lu"

	GSIZE_MODIFIER string = "l"

	GSSIZE_FORMAT string = "li"

	GSSIZE_MODIFIER string = "l"

	GUINT16_FORMAT string = "hu"

	GUINT32_FORMAT string = "u"

	GUINT64_FORMAT string = "lu"

	GUINTPTR_FORMAT string = "lu"

	HAVE_GINT64 int = 1

	HAVE_GNUC_VARARGS int = 1

	HAVE_GROWING_STACK int = 0

	HAVE_ISO_VARARGS int = 1
	// The major version number of the GLib library.
	//
	// Like #glib_major_version, but from the headers used at
	// application compile time, rather than from the library
	// linked against at application run time.
	MAJOR_VERSION int = 2
	// The micro version number of the GLib library.
	//
	// Like #gtk_micro_version, but from the headers used at
	// application compile time, rather than from the library
	// linked against at application run time.
	MICRO_VERSION int = 0
	// The minor version number of the GLib library.
	//
	// Like #gtk_minor_version, but from the headers used at
	// application compile time, rather than from the library
	// linked against at application run time.
	MINOR_VERSION int = 84

	MODULE_SUFFIX string = "so"
	// A format specifier that can be used in printf()-style format strings
	// when printing a #GPid.
	PID_FORMAT string = "i"
	// A format specifier that can be used in printf()-style format strings
	// when printing the @fd member of a #GPollFD.
	POLLFD_FORMAT string = "%d"
	// The search path separator character.
	// This is ':' on UNIX machines and ';' under Windows.
	SEARCHPATH_SEPARATOR int = 58
	// The search path separator as a string.
	// This is ":" on UNIX machines and ";" under Windows.
	SEARCHPATH_SEPARATOR_S string = ":"

	SIZEOF_LONG int = 8

	SIZEOF_SIZE_T int = 8

	SIZEOF_SSIZE_T int = 8

	SIZEOF_VOID_P int = 8

	SYSDEF_AF_INET int = 2

	SYSDEF_AF_INET6 int = 10

	SYSDEF_AF_UNIX int = 1

	SYSDEF_MSG_DONTROUTE int = 4

	SYSDEF_MSG_OOB int = 1

	SYSDEF_MSG_PEEK int = 2

	VA_COPY_AS_ARRAY int = 1
)
