// Package glib was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package glib

import (
	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/internal/core"
)

var xQsortWithData func(uintptr, int, uint, uintptr, uintptr)

// This is just like the standard C [`qsort()`](man:qsort(3)) function, but
// the comparison routine accepts a user data argument
// (like [`qsort_r()`](man:qsort_r(3))).
//
// Unlike `qsort()`, this is guaranteed to be a stable sort (since GLib 2.32).
func QsortWithData(PbaseVar uintptr, TotalElemsVar int, SizeVar uint, CompareFuncVar *CompareDataFunc, UserDataVar uintptr) {

	xQsortWithData(PbaseVar, TotalElemsVar, SizeVar, NewCallback(CompareFuncVar), UserDataVar)

}

var xSortArray func([]uintptr, uint, uint, uintptr, uintptr)

// This is just like the standard C [`qsort()`](man:qsort(3)) function, but
// the comparison routine accepts a user data argument
// (like [`qsort_r()`](man:qsort_r(3))).
//
// Unlike `qsort()`, this is guaranteed to be a stable sort.
func SortArray(ArrayVar []uintptr, NElementsVar uint, ElementSizeVar uint, CompareFuncVar *CompareDataFunc, UserDataVar uintptr) {

	xSortArray(ArrayVar, NElementsVar, ElementSizeVar, NewCallback(CompareFuncVar), UserDataVar)

}

func init() {
	lib, err := purego.Dlopen(core.GetPath("GLIB"), purego.RTLD_NOW|purego.RTLD_GLOBAL)
	if err != nil {
		panic(err)
	}

	core.PuregoSafeRegister(&xQsortWithData, lib, "g_qsort_with_data")
	core.PuregoSafeRegister(&xSortArray, lib, "g_sort_array")

}
