// Package glib was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package glib

import (
	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/internal/core"
)

var xSetPrgnameOnce func(string) bool

// If g_get_prgname() is not set, this is the same as setting
// the name via g_set_prgname() and %TRUE is returned. Otherwise,
// does nothing and returns %FALSE. This is thread-safe.
func SetPrgnameOnce(PrgnameVar string) bool {

	cret := xSetPrgnameOnce(PrgnameVar)
	return cret
}

var xSetUserDirs func(string, ...interface{})

func SetUserDirs(FirstDirTypeVar string, varArgs ...interface{}) {

	xSetUserDirs(FirstDirTypeVar, varArgs...)

}

func init() {
	lib, err := purego.Dlopen(core.GetPath("GLIB"), purego.RTLD_NOW|purego.RTLD_GLOBAL)
	if err != nil {
		panic(err)
	}

	core.PuregoSafeRegister(&xSetPrgnameOnce, lib, "g_set_prgname_once")
	core.PuregoSafeRegister(&xSetUserDirs, lib, "g_set_user_dirs")

}
