// Package glib was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package glib

import (
	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/internal/core"
)

var xVariantParserGetErrorQuark func() Quark

// Same as g_variant_error_quark().
func VariantParserGetErrorQuark() Quark {

	cret := xVariantParserGetErrorQuark()
	return cret
}

func init() {
	lib, err := purego.Dlopen(core.GetPath("GLIB"), purego.RTLD_NOW|purego.RTLD_GLOBAL)
	if err != nil {
		panic(err)
	}

	core.PuregoSafeRegister(&xVariantParserGetErrorQuark, lib, "g_variant_parser_get_error_quark")

}
