// Package gdk was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package gdk

import (
	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/internal/core"
)

var xColorStateGetOklab func() *ColorState

// Returns the color state object representing the oklab color space.
//
// This is a perceptually uniform color state.
func ColorStateGetOklab() *ColorState {

	cret := xColorStateGetOklab()
	return cret
}

var xColorStateGetOklch func() *ColorState

// Returns the color state object representing the oklch color space.
//
// This is the polar variant of oklab, in which the hue is encoded as
// a polar coordinate.
func ColorStateGetOklch() *ColorState {

	cret := xColorStateGetOklch()
	return cret
}

var xColorStateGetRec2100Linear func() *ColorState

// Returns the color state object representing the linear rec2100 color space.
//
// This color state uses the primaries defined by BT.2020-2 and BT.2100-0 and a linear
// transfer function.
//
// It is equivalent to the [Cicp](class.CicpParams.html) tuple 9/8/0/1.
//
// See e.g. [the CSS HDR Module](https://drafts.csswg.org/css-color-hdr/#valdef-color-rec2100-linear)
// for details about this colorstate.
func ColorStateGetRec2100Linear() *ColorState {

	cret := xColorStateGetRec2100Linear()
	return cret
}

var xColorStateGetRec2100Pq func() *ColorState

// Returns the color state object representing the rec2100-pq color space.
//
// This color state uses the primaries defined by BT.2020-2 and BT.2100-0 and the transfer
// function defined by SMPTE ST 2084 and BT.2100-2.
//
// It is equivalent to the [Cicp](class.CicpParams.html) tuple 9/16/0/1.
//
// See e.g. [the CSS HDR Module](https://drafts.csswg.org/css-color-hdr/#valdef-color-rec2100-pq)
// for details about this colorstate.
func ColorStateGetRec2100Pq() *ColorState {

	cret := xColorStateGetRec2100Pq()
	return cret
}

var xColorStateGetSrgb func() *ColorState

// Returns the color state object representing the sRGB color space.
//
// This color state uses the primaries defined by BT.709-6 and the transfer function
// defined by IEC 61966-2-1.
//
// It is equivalent to the [Cicp](class.CicpParams.html) tuple 1/13/0/1.
//
// See e.g. [the CSS Color Module](https://www.w3.org/TR/css-color-4/#predefined-sRGB)
// for details about this colorstate.
func ColorStateGetSrgb() *ColorState {

	cret := xColorStateGetSrgb()
	return cret
}

var xColorStateGetSrgbLinear func() *ColorState

// Returns the color state object representing the linearized sRGB color space.
//
// This color state uses the primaries defined by BT.709-6 and a linear transfer function.
//
// It is equivalent to the [Cicp](class.CicpParams.html) tuple 1/8/0/1.
//
// See e.g. [the CSS Color Module](https://www.w3.org/TR/css-color-4/#predefined-sRGB-linear)
// for details about this colorstate.
func ColorStateGetSrgbLinear() *ColorState {

	cret := xColorStateGetSrgbLinear()
	return cret
}

func init() {
	lib, err := purego.Dlopen(core.GetPath("GDK"), purego.RTLD_NOW|purego.RTLD_GLOBAL)
	if err != nil {
		panic(err)
	}

	core.PuregoSafeRegister(&xColorStateGetOklab, lib, "gdk_color_state_get_oklab")
	core.PuregoSafeRegister(&xColorStateGetOklch, lib, "gdk_color_state_get_oklch")
	core.PuregoSafeRegister(&xColorStateGetRec2100Linear, lib, "gdk_color_state_get_rec2100_linear")
	core.PuregoSafeRegister(&xColorStateGetRec2100Pq, lib, "gdk_color_state_get_rec2100_pq")
	core.PuregoSafeRegister(&xColorStateGetSrgb, lib, "gdk_color_state_get_srgb")
	core.PuregoSafeRegister(&xColorStateGetSrgbLinear, lib, "gdk_color_state_get_srgb_linear")

}
