// Package gdk was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package gdk

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/internal/core"
	"github.com/jwijenbergh/puregotk/v4/cairo"
	"github.com/jwijenbergh/puregotk/v4/glib"
	"github.com/jwijenbergh/puregotk/v4/gobject"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type DmabufTextureBuilderClass struct {
	_ structs.HostLayout
}

func (x *DmabufTextureBuilderClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

// Constructs [class@Gdk.Texture] objects from DMA buffers.
//
// DMA buffers are commonly called **_dma-bufs_**.
//
// DMA buffers are a feature of the Linux kernel to enable efficient buffer and
// memory sharing between hardware such as codecs, GPUs, displays, cameras and the
// kernel drivers controlling them. For example, a decoder may want its output to
// be directly shared with the display server for rendering without a copy.
//
// Any device driver which participates in DMA buffer sharing, can do so as either
// the exporter or importer of buffers (or both).
//
// The memory that is shared via DMA buffers is usually stored in non-system memory
// (maybe in device's local memory or something else not directly accessible by the
// CPU), and accessing this memory from the CPU may have higher-than-usual overhead.
//
// In particular for graphics data, it is not uncommon that data consists of multiple
// separate blocks of memory, for example one block for each of the red, green and
// blue channels. These blocks are called **_planes_**. DMA buffers can have up to
// four planes. Even if the memory is a single block, the data can be organized in
// multiple planes, by specifying offsets from the beginning of the data.
//
// DMA buffers are exposed to user-space as file descriptors allowing to pass them
// between processes. If a DMA buffer has multiple planes, there is one file
// descriptor per plane.
//
// The format of the data (for graphics data, essentially its colorspace) is described
// by a 32-bit integer. These format identifiers are defined in the header file `drm_fourcc.h`
// and commonly referred to as **_fourcc_** values, since they are identified by 4 ASCII
// characters. Additionally, each DMA buffer has a **_modifier_**, which is a 64-bit integer
// that describes driver-specific details of the memory layout, such as tiling or compression.
//
// For historical reasons, some producers of dma-bufs don't provide an explicit modifier, but
// instead return `DMA_FORMAT_MOD_INVALID` to indicate that their modifier is **_implicit_**.
// GTK tries to accommodate this situation by accepting `DMA_FORMAT_MOD_INVALID` as modifier.
//
// The operation of `GdkDmabufTextureBuilder` is quite simple: Create a texture builder,
// set all the necessary properties, and then call [method@Gdk.DmabufTextureBuilder.build]
// to create the new texture.
//
// The required properties for a dma-buf texture are
//
//   - The width and height in pixels
//
//   - The `fourcc` code and `modifier` which identify the format and memory layout of the dma-buf
//
//   - The file descriptor, offset and stride for each of the planes
//
// `GdkDmabufTextureBuilder` can be used for quick one-shot construction of
// textures as well as kept around and reused to construct multiple textures.
//
// # For further information, see
//
// * The Linux kernel [documentation](https://docs.kernel.org/driver-api/dma-buf.html)
//
// * The header file [drm_fourcc.h](https://gitlab.freedesktop.org/mesa/drm/-/blob/main/include/drm/drm_fourcc.h)
type DmabufTextureBuilder struct {
	gobject.Object
}

var xDmabufTextureBuilderGLibType func() types.GType

func DmabufTextureBuilderGLibType() types.GType {
	return xDmabufTextureBuilderGLibType()
}

func DmabufTextureBuilderNewFromInternalPtr(ptr uintptr) *DmabufTextureBuilder {
	cls := &DmabufTextureBuilder{}
	cls.Ptr = ptr
	return cls
}

var xNewDmabufTextureBuilder func() uintptr

// Creates a new texture builder.
func NewDmabufTextureBuilder() *DmabufTextureBuilder {
	var cls *DmabufTextureBuilder

	cret := xNewDmabufTextureBuilder()

	if cret == 0 {
		return nil
	}
	cls = &DmabufTextureBuilder{}
	cls.Ptr = cret
	return cls
}

var xDmabufTextureBuilderBuild func(uintptr, uintptr, uintptr, **glib.Error) uintptr

// Builds a new `GdkTexture` with the values set up in the builder.
//
// It is a programming error to call this function if any mandatory property has not been set.
//
// Not all formats defined in the `drm_fourcc.h` header are supported. You can use
// [method@Gdk.Display.get_dmabuf_formats] to get a list of supported formats. If the
// format is not supported by GTK, %NULL will be returned and @error will be set.
//
// The `destroy` function gets called when the returned texture gets released.
//
// It is the responsibility of the caller to keep the file descriptors for the planes
// open until the created texture is no longer used, and close them afterwards (possibly
// using the @destroy notify).
//
// It is possible to call this function multiple times to create multiple textures,
// possibly with changing properties in between.
func (x *DmabufTextureBuilder) Build(DestroyVar *glib.DestroyNotify, DataVar uintptr) (*Texture, error) {
	var cls *Texture
	var cerr *glib.Error

	cret := xDmabufTextureBuilderBuild(x.GoPointer(), glib.NewCallback(DestroyVar), DataVar, &cerr)

	if cret == 0 {
		return nil, cerr
	}
	cls = &Texture{}
	cls.Ptr = cret
	if cerr == nil {
		return cls, nil
	}
	return cls, cerr

}

var xDmabufTextureBuilderGetColorState func(uintptr) *ColorState

// Gets the color state previously set via gdk_dmabuf_texture_builder_set_color_state().
func (x *DmabufTextureBuilder) GetColorState() *ColorState {

	cret := xDmabufTextureBuilderGetColorState(x.GoPointer())
	return cret
}

var xDmabufTextureBuilderGetDisplay func(uintptr) uintptr

// Returns the display that this texture builder is
// associated with.
func (x *DmabufTextureBuilder) GetDisplay() *Display {
	var cls *Display

	cret := xDmabufTextureBuilderGetDisplay(x.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &Display{}
	cls.Ptr = cret
	return cls
}

var xDmabufTextureBuilderGetFd func(uintptr, uint) int

// Gets the file descriptor for a plane.
func (x *DmabufTextureBuilder) GetFd(PlaneVar uint) int {

	cret := xDmabufTextureBuilderGetFd(x.GoPointer(), PlaneVar)
	return cret
}

var xDmabufTextureBuilderGetFourcc func(uintptr) uint32

// Gets the format previously set via gdk_dmabuf_texture_builder_set_fourcc()
// or 0 if the format wasn't set.
//
// The format is specified as a fourcc code.
func (x *DmabufTextureBuilder) GetFourcc() uint32 {

	cret := xDmabufTextureBuilderGetFourcc(x.GoPointer())
	return cret
}

var xDmabufTextureBuilderGetHeight func(uintptr) uint

// Gets the height previously set via gdk_dmabuf_texture_builder_set_height() or
// 0 if the height wasn't set.
func (x *DmabufTextureBuilder) GetHeight() uint {

	cret := xDmabufTextureBuilderGetHeight(x.GoPointer())
	return cret
}

var xDmabufTextureBuilderGetModifier func(uintptr) uint64

// Gets the modifier value.
func (x *DmabufTextureBuilder) GetModifier() uint64 {

	cret := xDmabufTextureBuilderGetModifier(x.GoPointer())
	return cret
}

var xDmabufTextureBuilderGetNPlanes func(uintptr) uint

// Gets the number of planes.
func (x *DmabufTextureBuilder) GetNPlanes() uint {

	cret := xDmabufTextureBuilderGetNPlanes(x.GoPointer())
	return cret
}

var xDmabufTextureBuilderGetOffset func(uintptr, uint) uint

// Gets the offset value for a plane.
func (x *DmabufTextureBuilder) GetOffset(PlaneVar uint) uint {

	cret := xDmabufTextureBuilderGetOffset(x.GoPointer(), PlaneVar)
	return cret
}

var xDmabufTextureBuilderGetPremultiplied func(uintptr) bool

// Whether the data is premultiplied.
func (x *DmabufTextureBuilder) GetPremultiplied() bool {

	cret := xDmabufTextureBuilderGetPremultiplied(x.GoPointer())
	return cret
}

var xDmabufTextureBuilderGetStride func(uintptr, uint) uint

// Gets the stride value for a plane.
func (x *DmabufTextureBuilder) GetStride(PlaneVar uint) uint {

	cret := xDmabufTextureBuilderGetStride(x.GoPointer(), PlaneVar)
	return cret
}

var xDmabufTextureBuilderGetUpdateRegion func(uintptr) *cairo.Region

// Gets the region previously set via gdk_dmabuf_texture_builder_set_update_region() or
// %NULL if none was set.
func (x *DmabufTextureBuilder) GetUpdateRegion() *cairo.Region {

	cret := xDmabufTextureBuilderGetUpdateRegion(x.GoPointer())
	return cret
}

var xDmabufTextureBuilderGetUpdateTexture func(uintptr) uintptr

// Gets the texture previously set via gdk_dmabuf_texture_builder_set_update_texture() or
// %NULL if none was set.
func (x *DmabufTextureBuilder) GetUpdateTexture() *Texture {
	var cls *Texture

	cret := xDmabufTextureBuilderGetUpdateTexture(x.GoPointer())

	if cret == 0 {
		return nil
	}
	gobject.IncreaseRef(cret)
	cls = &Texture{}
	cls.Ptr = cret
	return cls
}

var xDmabufTextureBuilderGetWidth func(uintptr) uint

// Gets the width previously set via gdk_dmabuf_texture_builder_set_width() or
// 0 if the width wasn't set.
func (x *DmabufTextureBuilder) GetWidth() uint {

	cret := xDmabufTextureBuilderGetWidth(x.GoPointer())
	return cret
}

var xDmabufTextureBuilderSetColorState func(uintptr, *ColorState)

// Sets the color state for the texture.
//
// By default, the colorstate is `NULL`. In that case, GTK will choose the
// correct colorstate based on the format.
// If you don't know what colorstates are, this is probably the right thing.
func (x *DmabufTextureBuilder) SetColorState(ColorStateVar *ColorState) {

	xDmabufTextureBuilderSetColorState(x.GoPointer(), ColorStateVar)

}

var xDmabufTextureBuilderSetDisplay func(uintptr, uintptr)

// Sets the display that this texture builder is
// associated with.
//
// The display is used to determine the supported
// dma-buf formats.
func (x *DmabufTextureBuilder) SetDisplay(DisplayVar *Display) {

	xDmabufTextureBuilderSetDisplay(x.GoPointer(), DisplayVar.GoPointer())

}

var xDmabufTextureBuilderSetFd func(uintptr, uint, int)

// Sets the file descriptor for a plane.
func (x *DmabufTextureBuilder) SetFd(PlaneVar uint, FdVar int) {

	xDmabufTextureBuilderSetFd(x.GoPointer(), PlaneVar, FdVar)

}

var xDmabufTextureBuilderSetFourcc func(uintptr, uint32)

// Sets the format of the texture.
//
// The format is specified as a fourcc code.
//
// The format must be set before calling [method@Gdk.DmabufTextureBuilder.build].
func (x *DmabufTextureBuilder) SetFourcc(FourccVar uint32) {

	xDmabufTextureBuilderSetFourcc(x.GoPointer(), FourccVar)

}

var xDmabufTextureBuilderSetHeight func(uintptr, uint)

// Sets the height of the texture.
//
// The height must be set before calling [method@Gdk.DmabufTextureBuilder.build].
func (x *DmabufTextureBuilder) SetHeight(HeightVar uint) {

	xDmabufTextureBuilderSetHeight(x.GoPointer(), HeightVar)

}

var xDmabufTextureBuilderSetModifier func(uintptr, uint64)

// Sets the modifier.
func (x *DmabufTextureBuilder) SetModifier(ModifierVar uint64) {

	xDmabufTextureBuilderSetModifier(x.GoPointer(), ModifierVar)

}

var xDmabufTextureBuilderSetNPlanes func(uintptr, uint)

// Sets the number of planes of the texture.
func (x *DmabufTextureBuilder) SetNPlanes(NPlanesVar uint) {

	xDmabufTextureBuilderSetNPlanes(x.GoPointer(), NPlanesVar)

}

var xDmabufTextureBuilderSetOffset func(uintptr, uint, uint)

// Sets the offset for a plane.
func (x *DmabufTextureBuilder) SetOffset(PlaneVar uint, OffsetVar uint) {

	xDmabufTextureBuilderSetOffset(x.GoPointer(), PlaneVar, OffsetVar)

}

var xDmabufTextureBuilderSetPremultiplied func(uintptr, bool)

// Sets whether the data is premultiplied.
//
// Unless otherwise specified, all formats including alpha channels are assumed
// to be premultiplied.
func (x *DmabufTextureBuilder) SetPremultiplied(PremultipliedVar bool) {

	xDmabufTextureBuilderSetPremultiplied(x.GoPointer(), PremultipliedVar)

}

var xDmabufTextureBuilderSetStride func(uintptr, uint, uint)

// Sets the stride for a plane.
//
// The stride must be set for all planes before calling [method@Gdk.DmabufTextureBuilder.build].
func (x *DmabufTextureBuilder) SetStride(PlaneVar uint, StrideVar uint) {

	xDmabufTextureBuilderSetStride(x.GoPointer(), PlaneVar, StrideVar)

}

var xDmabufTextureBuilderSetUpdateRegion func(uintptr, *cairo.Region)

// Sets the region to be updated by this texture. Together with
// [property@Gdk.DmabufTextureBuilder:update-texture] this describes an
// update of a previous texture.
//
// When rendering animations of large textures, it is possible that
// consecutive textures are only updating contents in parts of the texture.
// It is then possible to describe this update via these two properties,
// so that GTK can avoid rerendering parts that did not change.
//
// An example would be a screen recording where only the mouse pointer moves.
func (x *DmabufTextureBuilder) SetUpdateRegion(RegionVar *cairo.Region) {

	xDmabufTextureBuilderSetUpdateRegion(x.GoPointer(), RegionVar)

}

var xDmabufTextureBuilderSetUpdateTexture func(uintptr, uintptr)

// Sets the texture to be updated by this texture. See
// [method@Gdk.DmabufTextureBuilder.set_update_region] for an explanation.
func (x *DmabufTextureBuilder) SetUpdateTexture(TextureVar *Texture) {

	xDmabufTextureBuilderSetUpdateTexture(x.GoPointer(), TextureVar.GoPointer())

}

var xDmabufTextureBuilderSetWidth func(uintptr, uint)

// Sets the width of the texture.
//
// The width must be set before calling [method@Gdk.DmabufTextureBuilder.build].
func (x *DmabufTextureBuilder) SetWidth(WidthVar uint) {

	xDmabufTextureBuilderSetWidth(x.GoPointer(), WidthVar)

}

func (c *DmabufTextureBuilder) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *DmabufTextureBuilder) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	lib, err := purego.Dlopen(core.GetPath("GDK"), purego.RTLD_NOW|purego.RTLD_GLOBAL)
	if err != nil {
		panic(err)
	}

	core.PuregoSafeRegister(&xDmabufTextureBuilderGLibType, lib, "gdk_dmabuf_texture_builder_get_type")

	core.PuregoSafeRegister(&xNewDmabufTextureBuilder, lib, "gdk_dmabuf_texture_builder_new")

	core.PuregoSafeRegister(&xDmabufTextureBuilderBuild, lib, "gdk_dmabuf_texture_builder_build")
	core.PuregoSafeRegister(&xDmabufTextureBuilderGetColorState, lib, "gdk_dmabuf_texture_builder_get_color_state")
	core.PuregoSafeRegister(&xDmabufTextureBuilderGetDisplay, lib, "gdk_dmabuf_texture_builder_get_display")
	core.PuregoSafeRegister(&xDmabufTextureBuilderGetFd, lib, "gdk_dmabuf_texture_builder_get_fd")
	core.PuregoSafeRegister(&xDmabufTextureBuilderGetFourcc, lib, "gdk_dmabuf_texture_builder_get_fourcc")
	core.PuregoSafeRegister(&xDmabufTextureBuilderGetHeight, lib, "gdk_dmabuf_texture_builder_get_height")
	core.PuregoSafeRegister(&xDmabufTextureBuilderGetModifier, lib, "gdk_dmabuf_texture_builder_get_modifier")
	core.PuregoSafeRegister(&xDmabufTextureBuilderGetNPlanes, lib, "gdk_dmabuf_texture_builder_get_n_planes")
	core.PuregoSafeRegister(&xDmabufTextureBuilderGetOffset, lib, "gdk_dmabuf_texture_builder_get_offset")
	core.PuregoSafeRegister(&xDmabufTextureBuilderGetPremultiplied, lib, "gdk_dmabuf_texture_builder_get_premultiplied")
	core.PuregoSafeRegister(&xDmabufTextureBuilderGetStride, lib, "gdk_dmabuf_texture_builder_get_stride")
	core.PuregoSafeRegister(&xDmabufTextureBuilderGetUpdateRegion, lib, "gdk_dmabuf_texture_builder_get_update_region")
	core.PuregoSafeRegister(&xDmabufTextureBuilderGetUpdateTexture, lib, "gdk_dmabuf_texture_builder_get_update_texture")
	core.PuregoSafeRegister(&xDmabufTextureBuilderGetWidth, lib, "gdk_dmabuf_texture_builder_get_width")
	core.PuregoSafeRegister(&xDmabufTextureBuilderSetColorState, lib, "gdk_dmabuf_texture_builder_set_color_state")
	core.PuregoSafeRegister(&xDmabufTextureBuilderSetDisplay, lib, "gdk_dmabuf_texture_builder_set_display")
	core.PuregoSafeRegister(&xDmabufTextureBuilderSetFd, lib, "gdk_dmabuf_texture_builder_set_fd")
	core.PuregoSafeRegister(&xDmabufTextureBuilderSetFourcc, lib, "gdk_dmabuf_texture_builder_set_fourcc")
	core.PuregoSafeRegister(&xDmabufTextureBuilderSetHeight, lib, "gdk_dmabuf_texture_builder_set_height")
	core.PuregoSafeRegister(&xDmabufTextureBuilderSetModifier, lib, "gdk_dmabuf_texture_builder_set_modifier")
	core.PuregoSafeRegister(&xDmabufTextureBuilderSetNPlanes, lib, "gdk_dmabuf_texture_builder_set_n_planes")
	core.PuregoSafeRegister(&xDmabufTextureBuilderSetOffset, lib, "gdk_dmabuf_texture_builder_set_offset")
	core.PuregoSafeRegister(&xDmabufTextureBuilderSetPremultiplied, lib, "gdk_dmabuf_texture_builder_set_premultiplied")
	core.PuregoSafeRegister(&xDmabufTextureBuilderSetStride, lib, "gdk_dmabuf_texture_builder_set_stride")
	core.PuregoSafeRegister(&xDmabufTextureBuilderSetUpdateRegion, lib, "gdk_dmabuf_texture_builder_set_update_region")
	core.PuregoSafeRegister(&xDmabufTextureBuilderSetUpdateTexture, lib, "gdk_dmabuf_texture_builder_set_update_texture")
	core.PuregoSafeRegister(&xDmabufTextureBuilderSetWidth, lib, "gdk_dmabuf_texture_builder_set_width")

}
