// Package gdk was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package gdk

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/internal/core"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

// Contains information that is useful to compute the size of a drag surface.
type DragSurfaceSize struct {
	_ structs.HostLayout
}

var xDragSurfaceSizeGLibType func() types.GType

func DragSurfaceSizeGLibType() types.GType {
	return xDragSurfaceSizeGLibType()
}

func (x *DragSurfaceSize) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

var xDragSurfaceSizeSetSize func(uintptr, int, int)

// Sets the size the drag surface prefers to be resized to.
func (x *DragSurfaceSize) SetSize(WidthVar int, HeightVar int) {

	xDragSurfaceSizeSetSize(x.GoPointer(), WidthVar, HeightVar)

}

func init() {
	lib, err := purego.Dlopen(core.GetPath("GDK"), purego.RTLD_NOW|purego.RTLD_GLOBAL)
	if err != nil {
		panic(err)
	}

	core.PuregoSafeRegister(&xDragSurfaceSizeGLibType, lib, "gdk_drag_surface_size_get_type")

	core.PuregoSafeRegister(&xDragSurfaceSizeSetSize, lib, "gdk_drag_surface_size_set_size")

}
