// Package gio was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package gio

import (
	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/internal/core"
	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

// `GSimpleIOStream` creates a [class@Gio.IOStream] from an arbitrary
// [class@Gio.InputStream] and [class@Gio.OutputStream]. This allows any pair of
// input and output streams to be used with [class@Gio.IOStream] methods.
//
// This is useful when you obtained a [class@Gio.InputStream] and a
// [class@Gio.OutputStream] by other means, for instance creating them with
// platform specific methods as
// [`g_unix_input_stream_new()`](../gio-unix/ctor.UnixInputStream.new.html)
// (from `gio-unix-2.0.pc` / `GioUnix-2.0`), and you want to
// take advantage of the methods provided by [class@Gio.IOStream].
type SimpleIOStream struct {
	IOStream
}

var xSimpleIOStreamGLibType func() types.GType

func SimpleIOStreamGLibType() types.GType {
	return xSimpleIOStreamGLibType()
}

func SimpleIOStreamNewFromInternalPtr(ptr uintptr) *SimpleIOStream {
	cls := &SimpleIOStream{}
	cls.Ptr = ptr
	return cls
}

var xNewSimpleIOStream func(uintptr, uintptr) uintptr

// Creates a new #GSimpleIOStream wrapping @input_stream and @output_stream.
// See also #GIOStream.
func NewSimpleIOStream(InputStreamVar *InputStream, OutputStreamVar *OutputStream) *SimpleIOStream {
	var cls *SimpleIOStream

	cret := xNewSimpleIOStream(InputStreamVar.GoPointer(), OutputStreamVar.GoPointer())

	if cret == 0 {
		return nil
	}
	cls = &SimpleIOStream{}
	cls.Ptr = cret
	return cls
}

func (c *SimpleIOStream) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *SimpleIOStream) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}

func init() {
	lib, err := purego.Dlopen(core.GetPath("GIO"), purego.RTLD_NOW|purego.RTLD_GLOBAL)
	if err != nil {
		panic(err)
	}

	core.PuregoSafeRegister(&xSimpleIOStreamGLibType, lib, "g_simple_io_stream_get_type")

	core.PuregoSafeRegister(&xNewSimpleIOStream, lib, "g_simple_io_stream_new")

}
