// Package gio was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package gio

import (
	"structs"
	"unsafe"

	"github.com/jwijenbergh/puregotk/v4/gobject/types"
)

type ThreadedResolverClass struct {
	_ structs.HostLayout

	ParentClass uintptr
}

func (x *ThreadedResolverClass) GoPointer() uintptr {
	return uintptr(unsafe.Pointer(x))
}

// #GThreadedResolver is an implementation of #GResolver which calls the libc
// lookup functions in threads to allow them to run asynchronously.
type ThreadedResolver struct {
	Resolver
}

var xThreadedResolverGLibType func() types.GType

func ThreadedResolverGLibType() types.GType {
	return xThreadedResolverGLibType()
}

func ThreadedResolverNewFromInternalPtr(ptr uintptr) *ThreadedResolver {
	cls := &ThreadedResolver{}
	cls.Ptr = ptr
	return cls
}

func (c *ThreadedResolver) GoPointer() uintptr {
	if c == nil {
		return 0
	}
	return c.Ptr
}

func (c *ThreadedResolver) SetGoPointer(ptr uintptr) {
	c.Ptr = ptr
}
