// Package gsk was automatically generated by github.com/jwijenbergh/puregotk DO NOT EDIT
package gsk

import (
	"github.com/jwijenbergh/purego"
	"github.com/jwijenbergh/puregotk/internal/core"
)

var xStrokeEqual func(uintptr, uintptr) bool

// Checks if two strokes are identical.
func StrokeEqual(Stroke1Var uintptr, Stroke2Var uintptr) bool {

	cret := xStrokeEqual(Stroke1Var, Stroke2Var)
	return cret
}

func init() {
	lib, err := purego.Dlopen(core.GetPath("GSK"), purego.RTLD_NOW|purego.RTLD_GLOBAL)
	if err != nil {
		panic(err)
	}

	core.PuregoSafeRegister(&xStrokeEqual, lib, "gsk_stroke_equal")

}
